/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.111
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIBTFSValueNumber-772.h
 *
 * 
 */

#ifndef OAIBTFSValueNumber-772_H_
#define OAIBTFSValueNumber-772_H_

#include <QJsonObject>


#include "OAIBTFSValue-1888.h"
#include <QString>

#include "OAIObject.h"

namespace OpenAPI {

class OAIBTFSValueNumber-772: public OAIObject {
public:
    OAIBTFSValueNumber-772();
    OAIBTFSValueNumber-772(QString json);
    ~OAIBTFSValueNumber-772();
    void init();
    void cleanup();

    QString asJson () override;
    QJsonObject asJsonObject() override;
    void fromJsonObject(QJsonObject json) override;
    OAIBTFSValueNumber-772* fromJson(QString jsonString) override;

    QString* getBtType();
    void setBtType(QString* bt_type);

    QString* getConfigurationValueString();
    void setConfigurationValueString(QString* configuration_value_string);

    QString* getTypeTag();
    void setTypeTag(QString* type_tag);

    double getValueObject();
    void setValueObject(double value_object);

    double getValue();
    void setValue(double value);


    virtual bool isSet() override;

private:
    QString* bt_type;
    bool m_bt_type_isSet;

    QString* configuration_value_string;
    bool m_configuration_value_string_isSet;

    QString* type_tag;
    bool m_type_tag_isSet;

    double value_object;
    bool m_value_object_isSet;

    double value;
    bool m_value_isSet;

};

}

#endif /* OAIBTFSValueNumber-772_H_ */
