/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.111
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIBTMParameterLookupTablePath-1419.h
 *
 * 
 */

#ifndef OAIBTMParameterLookupTablePath-1419_H_
#define OAIBTMParameterLookupTablePath-1419_H_

#include <QJsonObject>


#include "OAIBTMParameter-1.h"
#include <QList>
#include <QMap>
#include <QString>

#include "OAIObject.h"

namespace OpenAPI {

class OAIBTMParameterLookupTablePath-1419: public OAIObject {
public:
    OAIBTMParameterLookupTablePath-1419();
    OAIBTMParameterLookupTablePath-1419(QString json);
    ~OAIBTMParameterLookupTablePath-1419();
    void init();
    void cleanup();

    QString asJson () override;
    QJsonObject asJsonObject() override;
    void fromJsonObject(QJsonObject json) override;
    OAIBTMParameterLookupTablePath-1419* fromJson(QString jsonString) override;

    QString* getBtType();
    void setBtType(QString* bt_type);

    QString* getImportMicroversion();
    void setImportMicroversion(QString* import_microversion);

    QString* getNodeId();
    void setNodeId(QString* node_id);

    QString* getParameterId();
    void setParameterId(QString* parameter_id);

    QMap<QString, QString*>* getValue();
    void setValue(QMap<QString, QString*>* value);


    virtual bool isSet() override;

private:
    QString* bt_type;
    bool m_bt_type_isSet;

    QString* import_microversion;
    bool m_import_microversion_isSet;

    QString* node_id;
    bool m_node_id_isSet;

    QString* parameter_id;
    bool m_parameter_id_isSet;

    QMap<QString, QString*>* value;
    bool m_value_isSet;

};

}

#endif /* OAIBTMParameterLookupTablePath-1419_H_ */
