/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.111
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIBTBoundingBoxInfo.h
 *
 * 
 */

#ifndef OAIBTBoundingBoxInfo_H_
#define OAIBTBoundingBoxInfo_H_

#include <QJsonObject>



#include "OAIObject.h"

namespace OpenAPI {

class OAIBTBoundingBoxInfo: public OAIObject {
public:
    OAIBTBoundingBoxInfo();
    OAIBTBoundingBoxInfo(QString json);
    ~OAIBTBoundingBoxInfo();
    void init();
    void cleanup();

    QString asJson () override;
    QJsonObject asJsonObject() override;
    void fromJsonObject(QJsonObject json) override;
    OAIBTBoundingBoxInfo* fromJson(QString jsonString) override;

    double getHighX();
    void setHighX(double high_x);

    double getHighY();
    void setHighY(double high_y);

    double getHighZ();
    void setHighZ(double high_z);

    double getLowX();
    void setLowX(double low_x);

    double getLowY();
    void setLowY(double low_y);

    double getLowZ();
    void setLowZ(double low_z);


    virtual bool isSet() override;

private:
    double high_x;
    bool m_high_x_isSet;

    double high_y;
    bool m_high_y_isSet;

    double high_z;
    bool m_high_z_isSet;

    double low_x;
    bool m_low_x_isSet;

    double low_y;
    bool m_low_y_isSet;

    double low_z;
    bool m_low_z_isSet;

};

}

#endif /* OAIBTBoundingBoxInfo_H_ */
