/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.111
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIBTInsertablesListResponse.h
 *
 * 
 */

#ifndef OAIBTInsertablesListResponse_H_
#define OAIBTInsertablesListResponse_H_

#include <QJsonObject>


#include "OAIBTInsertableInfo.h"
#include <QList>
#include <QString>

#include "OAIObject.h"

namespace OpenAPI {

class OAIBTInsertablesListResponse: public OAIObject {
public:
    OAIBTInsertablesListResponse();
    OAIBTInsertablesListResponse(QString json);
    ~OAIBTInsertablesListResponse();
    void init();
    void cleanup();

    QString asJson () override;
    QJsonObject asJsonObject() override;
    void fromJsonObject(QJsonObject json) override;
    OAIBTInsertablesListResponse* fromJson(QString jsonString) override;

    bool isCanSaveVersion();
    void setCanSaveVersion(bool can_save_version);

    qint32 getChangesSinceVersionSave();
    void setChangesSinceVersionSave(qint32 changes_since_version_save);

    bool isHasMultipleVersions();
    void setHasMultipleVersions(bool has_multiple_versions);

    QString* getHref();
    void setHref(QString* href);

    QList<OAIBTInsertableInfo*>* getItems();
    void setItems(QList<OAIBTInsertableInfo*>* items);

    QString* getNext();
    void setNext(QString* next);

    QString* getPrevious();
    void setPrevious(QString* previous);


    virtual bool isSet() override;

private:
    bool can_save_version;
    bool m_can_save_version_isSet;

    qint32 changes_since_version_save;
    bool m_changes_since_version_save_isSet;

    bool has_multiple_versions;
    bool m_has_multiple_versions_isSet;

    QString* href;
    bool m_href_isSet;

    QList<OAIBTInsertableInfo*>* items;
    bool m_items_isSet;

    QString* next;
    bool m_next_isSet;

    QString* previous;
    bool m_previous_isSet;

};

}

#endif /* OAIBTInsertablesListResponse_H_ */
