/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.111
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIBTConfigurationParams.h
 *
 * 
 */

#ifndef OAIBTConfigurationParams_H_
#define OAIBTConfigurationParams_H_

#include <QJsonObject>


#include "OAIConfigurationEntry.h"
#include <QList>
#include <QString>

#include "OAIObject.h"

namespace OpenAPI {

class OAIBTConfigurationParams: public OAIObject {
public:
    OAIBTConfigurationParams();
    OAIBTConfigurationParams(QString json);
    ~OAIBTConfigurationParams();
    void init();
    void cleanup();

    QString asJson () override;
    QJsonObject asJsonObject() override;
    void fromJsonObject(QJsonObject json) override;
    OAIBTConfigurationParams* fromJson(QString jsonString) override;

    QList<OAIConfigurationEntry*>* getParameters();
    void setParameters(QList<OAIConfigurationEntry*>* parameters);

    QString* getStandardContentParametersId();
    void setStandardContentParametersId(QString* standard_content_parameters_id);


    virtual bool isSet() override;

private:
    QList<OAIConfigurationEntry*>* parameters;
    bool m_parameters_isSet;

    QString* standard_content_parameters_id;
    bool m_standard_content_parameters_id_isSet;

};

}

#endif /* OAIBTConfigurationParams_H_ */
