/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.111
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIBTCommonUnitsInfo.h
 *
 * 
 */

#ifndef OAIBTCommonUnitsInfo_H_
#define OAIBTCommonUnitsInfo_H_

#include <QJsonObject>


#include "OAIBTCommonUnitInfo.h"
#include <QList>

#include "OAIObject.h"

namespace OpenAPI {

class OAIBTCommonUnitsInfo: public OAIObject {
public:
    OAIBTCommonUnitsInfo();
    OAIBTCommonUnitsInfo(QString json);
    ~OAIBTCommonUnitsInfo();
    void init();
    void cleanup();

    QString asJson () override;
    QJsonObject asJsonObject() override;
    void fromJsonObject(QJsonObject json) override;
    OAIBTCommonUnitsInfo* fromJson(QString jsonString) override;

    QList<OAIBTCommonUnitInfo*>* getUnits();
    void setUnits(QList<OAIBTCommonUnitInfo*>* units);


    virtual bool isSet() override;

private:
    QList<OAIBTCommonUnitInfo*>* units;
    bool m_units_isSet;

};

}

#endif /* OAIBTCommonUnitsInfo_H_ */
