/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.111
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIBTFSValueString-1422.h
 *
 * 
 */

#ifndef OAIBTFSValueString-1422_H_
#define OAIBTFSValueString-1422_H_

#include <QJsonObject>


#include "OAIBTFSValue-1888.h"
#include <QString>

#include "OAIObject.h"

namespace OpenAPI {

class OAIBTFSValueString-1422: public OAIObject {
public:
    OAIBTFSValueString-1422();
    OAIBTFSValueString-1422(QString json);
    ~OAIBTFSValueString-1422();
    void init();
    void cleanup();

    QString asJson () override;
    QJsonObject asJsonObject() override;
    void fromJsonObject(QJsonObject json) override;
    OAIBTFSValueString-1422* fromJson(QString jsonString) override;

    QString* getBtType();
    void setBtType(QString* bt_type);

    QString* getConfigurationValueString();
    void setConfigurationValueString(QString* configuration_value_string);

    QString* getTypeTag();
    void setTypeTag(QString* type_tag);

    QString* getValueObject();
    void setValueObject(QString* value_object);

    QString* getValue();
    void setValue(QString* value);


    virtual bool isSet() override;

private:
    QString* bt_type;
    bool m_bt_type_isSet;

    QString* configuration_value_string;
    bool m_configuration_value_string_isSet;

    QString* type_tag;
    bool m_type_tag_isSet;

    QString* value_object;
    bool m_value_object_isSet;

    QString* value;
    bool m_value_isSet;

};

}

#endif /* OAIBTFSValueString-1422_H_ */
