/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.111
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIBTMParameterString-149.h
 *
 * 
 */

#ifndef OAIBTMParameterString-149_H_
#define OAIBTMParameterString-149_H_

#include <QJsonObject>


#include "OAIBTMParameter-1.h"
#include <QString>

#include "OAIObject.h"

namespace OpenAPI {

class OAIBTMParameterString-149: public OAIObject {
public:
    OAIBTMParameterString-149();
    OAIBTMParameterString-149(QString json);
    ~OAIBTMParameterString-149();
    void init();
    void cleanup();

    QString asJson () override;
    QJsonObject asJsonObject() override;
    void fromJsonObject(QJsonObject json) override;
    OAIBTMParameterString-149* fromJson(QString jsonString) override;

    QString* getBtType();
    void setBtType(QString* bt_type);

    QString* getImportMicroversion();
    void setImportMicroversion(QString* import_microversion);

    QString* getNodeId();
    void setNodeId(QString* node_id);

    QString* getParameterId();
    void setParameterId(QString* parameter_id);

    QString* getValue();
    void setValue(QString* value);


    virtual bool isSet() override;

private:
    QString* bt_type;
    bool m_bt_type_isSet;

    QString* import_microversion;
    bool m_import_microversion_isSet;

    QString* node_id;
    bool m_node_id_isSet;

    QString* parameter_id;
    bool m_parameter_id_isSet;

    QString* value;
    bool m_value_isSet;

};

}

#endif /* OAIBTMParameterString-149_H_ */
