/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.111
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


#include "OAIBTPExpressionCall-240.h"

#include "OAIHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace OpenAPI {

OAIBTPExpressionCall-240::OAIBTPExpressionCall-240(QString json) {
    init();
    this->fromJson(json);
}

OAIBTPExpressionCall-240::OAIBTPExpressionCall-240() {
    init();
}

OAIBTPExpressionCall-240::~OAIBTPExpressionCall-240() {
    this->cleanup();
}

void
OAIBTPExpressionCall-240::init() {
    atomic = false;
    m_atomic_isSet = false;
    bt_type = new QString("");
    m_bt_type_isSet = false;
    documentation_type = new QString("");
    m_documentation_type_isSet = false;
    end_source_location = 0;
    m_end_source_location_isSet = false;
    node_id = new QString("");
    m_node_id_isSet = false;
    short_descriptor = new QString("");
    m_short_descriptor_isSet = false;
    space_after = new OAIBTPSpace-10();
    m_space_after_isSet = false;
    space_before = new OAIBTPSpace-10();
    m_space_before_isSet = false;
    space_default = false;
    m_space_default_isSet = false;
    start_source_location = 0;
    m_start_source_location_isSet = false;
    arguments = new QList<OAIBTPExpression-9*>();
    m_arguments_isSet = false;
    function_name = new OAIBTPName-261();
    m_function_name_isSet = false;
    function_name_string = new QString("");
    m_function_name_string_isSet = false;
    function_expression = new OAIBTPExpression-9();
    m_function_expression_isSet = false;
    space_in_empty_list = new OAIBTPSpace-10();
    m_space_in_empty_list_isSet = false;
}

void
OAIBTPExpressionCall-240::cleanup() {

    if(bt_type != nullptr) { 
        delete bt_type;
    }
    if(documentation_type != nullptr) { 
        delete documentation_type;
    }

    if(node_id != nullptr) { 
        delete node_id;
    }
    if(short_descriptor != nullptr) { 
        delete short_descriptor;
    }
    if(space_after != nullptr) { 
        delete space_after;
    }
    if(space_before != nullptr) { 
        delete space_before;
    }


    if(arguments != nullptr) { 
        auto arr = arguments;
        for(auto o: *arr) { 
            delete o;
        }
        delete arguments;
    }
    if(function_name != nullptr) { 
        delete function_name;
    }
    if(function_name_string != nullptr) { 
        delete function_name_string;
    }
    if(function_expression != nullptr) { 
        delete function_expression;
    }
    if(space_in_empty_list != nullptr) { 
        delete space_in_empty_list;
    }
}

OAIBTPExpressionCall-240*
OAIBTPExpressionCall-240::fromJson(QString json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
OAIBTPExpressionCall-240::fromJsonObject(QJsonObject pJson) {
    ::OpenAPI::setValue(&atomic, pJson["atomic"], "bool", "");
    
    ::OpenAPI::setValue(&bt_type, pJson["btType"], "QString", "QString");
    
    ::OpenAPI::setValue(&documentation_type, pJson["documentationType"], "QString", "QString");
    
    ::OpenAPI::setValue(&end_source_location, pJson["endSourceLocation"], "qint32", "");
    
    ::OpenAPI::setValue(&node_id, pJson["nodeId"], "QString", "QString");
    
    ::OpenAPI::setValue(&short_descriptor, pJson["shortDescriptor"], "QString", "QString");
    
    ::OpenAPI::setValue(&space_after, pJson["spaceAfter"], "OAIBTPSpace-10", "OAIBTPSpace-10");
    
    ::OpenAPI::setValue(&space_before, pJson["spaceBefore"], "OAIBTPSpace-10", "OAIBTPSpace-10");
    
    ::OpenAPI::setValue(&space_default, pJson["spaceDefault"], "bool", "");
    
    ::OpenAPI::setValue(&start_source_location, pJson["startSourceLocation"], "qint32", "");
    
    
    ::OpenAPI::setValue(&arguments, pJson["arguments"], "QList", "OAIBTPExpression-9");
    ::OpenAPI::setValue(&function_name, pJson["functionName"], "OAIBTPName-261", "OAIBTPName-261");
    
    ::OpenAPI::setValue(&function_name_string, pJson["functionNameString"], "QString", "QString");
    
    ::OpenAPI::setValue(&function_expression, pJson["functionExpression"], "OAIBTPExpression-9", "OAIBTPExpression-9");
    
    ::OpenAPI::setValue(&space_in_empty_list, pJson["spaceInEmptyList"], "OAIBTPSpace-10", "OAIBTPSpace-10");
    
}

QString
OAIBTPExpressionCall-240::asJson ()
{
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject
OAIBTPExpressionCall-240::asJsonObject() {
    QJsonObject obj;
    if(m_atomic_isSet){
        obj.insert("atomic", QJsonValue(atomic));
    }
    if(bt_type != nullptr && *bt_type != QString("")){
        toJsonValue(QString("btType"), bt_type, obj, QString("QString"));
    }
    if(documentation_type != nullptr && *documentation_type != QString("")){
        toJsonValue(QString("documentationType"), documentation_type, obj, QString("QString"));
    }
    if(m_end_source_location_isSet){
        obj.insert("endSourceLocation", QJsonValue(end_source_location));
    }
    if(node_id != nullptr && *node_id != QString("")){
        toJsonValue(QString("nodeId"), node_id, obj, QString("QString"));
    }
    if(short_descriptor != nullptr && *short_descriptor != QString("")){
        toJsonValue(QString("shortDescriptor"), short_descriptor, obj, QString("QString"));
    }
    if((space_after != nullptr) && (space_after->isSet())){
        toJsonValue(QString("spaceAfter"), space_after, obj, QString("OAIBTPSpace-10"));
    }
    if((space_before != nullptr) && (space_before->isSet())){
        toJsonValue(QString("spaceBefore"), space_before, obj, QString("OAIBTPSpace-10"));
    }
    if(m_space_default_isSet){
        obj.insert("spaceDefault", QJsonValue(space_default));
    }
    if(m_start_source_location_isSet){
        obj.insert("startSourceLocation", QJsonValue(start_source_location));
    }
    if(arguments->size() > 0){
        toJsonArray((QList<void*>*)arguments, obj, "arguments", "OAIBTPExpression-9");
    }
    if((function_name != nullptr) && (function_name->isSet())){
        toJsonValue(QString("functionName"), function_name, obj, QString("OAIBTPName-261"));
    }
    if(function_name_string != nullptr && *function_name_string != QString("")){
        toJsonValue(QString("functionNameString"), function_name_string, obj, QString("QString"));
    }
    if((function_expression != nullptr) && (function_expression->isSet())){
        toJsonValue(QString("functionExpression"), function_expression, obj, QString("OAIBTPExpression-9"));
    }
    if((space_in_empty_list != nullptr) && (space_in_empty_list->isSet())){
        toJsonValue(QString("spaceInEmptyList"), space_in_empty_list, obj, QString("OAIBTPSpace-10"));
    }

    return obj;
}

bool
OAIBTPExpressionCall-240::isAtomic() {
    return atomic;
}
void
OAIBTPExpressionCall-240::setAtomic(bool atomic) {
    this->atomic = atomic;
    this->m_atomic_isSet = true;
}

QString*
OAIBTPExpressionCall-240::getBtType() {
    return bt_type;
}
void
OAIBTPExpressionCall-240::setBtType(QString* bt_type) {
    this->bt_type = bt_type;
    this->m_bt_type_isSet = true;
}

QString*
OAIBTPExpressionCall-240::getDocumentationType() {
    return documentation_type;
}
void
OAIBTPExpressionCall-240::setDocumentationType(QString* documentation_type) {
    this->documentation_type = documentation_type;
    this->m_documentation_type_isSet = true;
}

qint32
OAIBTPExpressionCall-240::getEndSourceLocation() {
    return end_source_location;
}
void
OAIBTPExpressionCall-240::setEndSourceLocation(qint32 end_source_location) {
    this->end_source_location = end_source_location;
    this->m_end_source_location_isSet = true;
}

QString*
OAIBTPExpressionCall-240::getNodeId() {
    return node_id;
}
void
OAIBTPExpressionCall-240::setNodeId(QString* node_id) {
    this->node_id = node_id;
    this->m_node_id_isSet = true;
}

QString*
OAIBTPExpressionCall-240::getShortDescriptor() {
    return short_descriptor;
}
void
OAIBTPExpressionCall-240::setShortDescriptor(QString* short_descriptor) {
    this->short_descriptor = short_descriptor;
    this->m_short_descriptor_isSet = true;
}

OAIBTPSpace-10*
OAIBTPExpressionCall-240::getSpaceAfter() {
    return space_after;
}
void
OAIBTPExpressionCall-240::setSpaceAfter(OAIBTPSpace-10* space_after) {
    this->space_after = space_after;
    this->m_space_after_isSet = true;
}

OAIBTPSpace-10*
OAIBTPExpressionCall-240::getSpaceBefore() {
    return space_before;
}
void
OAIBTPExpressionCall-240::setSpaceBefore(OAIBTPSpace-10* space_before) {
    this->space_before = space_before;
    this->m_space_before_isSet = true;
}

bool
OAIBTPExpressionCall-240::isSpaceDefault() {
    return space_default;
}
void
OAIBTPExpressionCall-240::setSpaceDefault(bool space_default) {
    this->space_default = space_default;
    this->m_space_default_isSet = true;
}

qint32
OAIBTPExpressionCall-240::getStartSourceLocation() {
    return start_source_location;
}
void
OAIBTPExpressionCall-240::setStartSourceLocation(qint32 start_source_location) {
    this->start_source_location = start_source_location;
    this->m_start_source_location_isSet = true;
}

QList<OAIBTPExpression-9*>*
OAIBTPExpressionCall-240::getArguments() {
    return arguments;
}
void
OAIBTPExpressionCall-240::setArguments(QList<OAIBTPExpression-9*>* arguments) {
    this->arguments = arguments;
    this->m_arguments_isSet = true;
}

OAIBTPName-261*
OAIBTPExpressionCall-240::getFunctionName() {
    return function_name;
}
void
OAIBTPExpressionCall-240::setFunctionName(OAIBTPName-261* function_name) {
    this->function_name = function_name;
    this->m_function_name_isSet = true;
}

QString*
OAIBTPExpressionCall-240::getFunctionNameString() {
    return function_name_string;
}
void
OAIBTPExpressionCall-240::setFunctionNameString(QString* function_name_string) {
    this->function_name_string = function_name_string;
    this->m_function_name_string_isSet = true;
}

OAIBTPExpression-9*
OAIBTPExpressionCall-240::getFunctionExpression() {
    return function_expression;
}
void
OAIBTPExpressionCall-240::setFunctionExpression(OAIBTPExpression-9* function_expression) {
    this->function_expression = function_expression;
    this->m_function_expression_isSet = true;
}

OAIBTPSpace-10*
OAIBTPExpressionCall-240::getSpaceInEmptyList() {
    return space_in_empty_list;
}
void
OAIBTPExpressionCall-240::setSpaceInEmptyList(OAIBTPSpace-10* space_in_empty_list) {
    this->space_in_empty_list = space_in_empty_list;
    this->m_space_in_empty_list_isSet = true;
}


bool
OAIBTPExpressionCall-240::isSet(){
    bool isObjectUpdated = false;
    do{
        if(m_atomic_isSet){ isObjectUpdated = true; break;}
        if(bt_type != nullptr && *bt_type != QString("")){ isObjectUpdated = true; break;}
        if(documentation_type != nullptr && *documentation_type != QString("")){ isObjectUpdated = true; break;}
        if(m_end_source_location_isSet){ isObjectUpdated = true; break;}
        if(node_id != nullptr && *node_id != QString("")){ isObjectUpdated = true; break;}
        if(short_descriptor != nullptr && *short_descriptor != QString("")){ isObjectUpdated = true; break;}
        if(space_after != nullptr && space_after->isSet()){ isObjectUpdated = true; break;}
        if(space_before != nullptr && space_before->isSet()){ isObjectUpdated = true; break;}
        if(m_space_default_isSet){ isObjectUpdated = true; break;}
        if(m_start_source_location_isSet){ isObjectUpdated = true; break;}
        if(arguments->size() > 0){ isObjectUpdated = true; break;}
        if(function_name != nullptr && function_name->isSet()){ isObjectUpdated = true; break;}
        if(function_name_string != nullptr && *function_name_string != QString("")){ isObjectUpdated = true; break;}
        if(function_expression != nullptr && function_expression->isSet()){ isObjectUpdated = true; break;}
        if(space_in_empty_list != nullptr && space_in_empty_list->isSet()){ isObjectUpdated = true; break;}
    }while(false);
    return isObjectUpdated;
}
}

