/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.111
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIBTMetadataPropertyConfigSummaryInfo.h
 *
 * 
 */

#ifndef OAIBTMetadataPropertyConfigSummaryInfo_H_
#define OAIBTMetadataPropertyConfigSummaryInfo_H_

#include <QJsonObject>


#include "OAIBTMetadataCategorySummaryInfo.h"
#include <QString>

#include "OAIObject.h"

namespace OpenAPI {

class OAIBTMetadataPropertyConfigSummaryInfo: public OAIObject {
public:
    OAIBTMetadataPropertyConfigSummaryInfo();
    OAIBTMetadataPropertyConfigSummaryInfo(QString json);
    ~OAIBTMetadataPropertyConfigSummaryInfo();
    void init();
    void cleanup();

    QString asJson () override;
    QJsonObject asJsonObject() override;
    void fromJsonObject(QJsonObject json) override;
    OAIBTMetadataPropertyConfigSummaryInfo* fromJson(QString jsonString) override;

    QString* getCategoryId();
    void setCategoryId(QString* category_id);

    OAIBTMetadataCategorySummaryInfo* getCategorySummaryInfo();
    void setCategorySummaryInfo(OAIBTMetadataCategorySummaryInfo* category_summary_info);

    QString* getDisplayName();
    void setDisplayName(QString* display_name);

    qint32 getObjectType();
    void setObjectType(qint32 object_type);

    QString* getPropertyId();
    void setPropertyId(QString* property_id);

    qint32 getPublishState();
    void setPublishState(qint32 publish_state);

    QString* getSchemaId();
    void setSchemaId(QString* schema_id);


    virtual bool isSet() override;

private:
    QString* category_id;
    bool m_category_id_isSet;

    OAIBTMetadataCategorySummaryInfo* category_summary_info;
    bool m_category_summary_info_isSet;

    QString* display_name;
    bool m_display_name_isSet;

    qint32 object_type;
    bool m_object_type_isSet;

    QString* property_id;
    bool m_property_id_isSet;

    qint32 publish_state;
    bool m_publish_state_isSet;

    QString* schema_id;
    bool m_schema_id_isSet;

};

}

#endif /* OAIBTMetadataPropertyConfigSummaryInfo_H_ */
