/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.111
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


#include "OAIBTConfigurationResponse-2019.h"

#include "OAIHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace OpenAPI {

OAIBTConfigurationResponse-2019::OAIBTConfigurationResponse-2019(QString json) {
    init();
    this->fromJson(json);
}

OAIBTConfigurationResponse-2019::OAIBTConfigurationResponse-2019() {
    init();
}

OAIBTConfigurationResponse-2019::~OAIBTConfigurationResponse-2019() {
    this->cleanup();
}

void
OAIBTConfigurationResponse-2019::init() {
    configuration_parameters = new QList<OAIBTMConfigurationParameter-819*>();
    m_configuration_parameters_isSet = false;
    current_configuration = new QList<OAIBTMParameter-1*>();
    m_current_configuration_isSet = false;
    library_version = 0;
    m_library_version_isSet = false;
    microversion_skew = false;
    m_microversion_skew_isSet = false;
    reject_microversion_skew = false;
    m_reject_microversion_skew_isSet = false;
    serialization_version = new QString("");
    m_serialization_version_isSet = false;
    source_microversion = new QString("");
    m_source_microversion_isSet = false;
}

void
OAIBTConfigurationResponse-2019::cleanup() {
    if(configuration_parameters != nullptr) { 
        auto arr = configuration_parameters;
        for(auto o: *arr) { 
            delete o;
        }
        delete configuration_parameters;
    }
    if(current_configuration != nullptr) { 
        auto arr = current_configuration;
        for(auto o: *arr) { 
            delete o;
        }
        delete current_configuration;
    }



    if(serialization_version != nullptr) { 
        delete serialization_version;
    }
    if(source_microversion != nullptr) { 
        delete source_microversion;
    }
}

OAIBTConfigurationResponse-2019*
OAIBTConfigurationResponse-2019::fromJson(QString json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
OAIBTConfigurationResponse-2019::fromJsonObject(QJsonObject pJson) {
    
    ::OpenAPI::setValue(&configuration_parameters, pJson["configurationParameters"], "QList", "OAIBTMConfigurationParameter-819");
    
    ::OpenAPI::setValue(&current_configuration, pJson["currentConfiguration"], "QList", "OAIBTMParameter-1");
    ::OpenAPI::setValue(&library_version, pJson["libraryVersion"], "qint32", "");
    
    ::OpenAPI::setValue(&microversion_skew, pJson["microversionSkew"], "bool", "");
    
    ::OpenAPI::setValue(&reject_microversion_skew, pJson["rejectMicroversionSkew"], "bool", "");
    
    ::OpenAPI::setValue(&serialization_version, pJson["serializationVersion"], "QString", "QString");
    
    ::OpenAPI::setValue(&source_microversion, pJson["sourceMicroversion"], "QString", "QString");
    
}

QString
OAIBTConfigurationResponse-2019::asJson ()
{
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject
OAIBTConfigurationResponse-2019::asJsonObject() {
    QJsonObject obj;
    if(configuration_parameters->size() > 0){
        toJsonArray((QList<void*>*)configuration_parameters, obj, "configurationParameters", "OAIBTMConfigurationParameter-819");
    }
    if(current_configuration->size() > 0){
        toJsonArray((QList<void*>*)current_configuration, obj, "currentConfiguration", "OAIBTMParameter-1");
    }
    if(m_library_version_isSet){
        obj.insert("libraryVersion", QJsonValue(library_version));
    }
    if(m_microversion_skew_isSet){
        obj.insert("microversionSkew", QJsonValue(microversion_skew));
    }
    if(m_reject_microversion_skew_isSet){
        obj.insert("rejectMicroversionSkew", QJsonValue(reject_microversion_skew));
    }
    if(serialization_version != nullptr && *serialization_version != QString("")){
        toJsonValue(QString("serializationVersion"), serialization_version, obj, QString("QString"));
    }
    if(source_microversion != nullptr && *source_microversion != QString("")){
        toJsonValue(QString("sourceMicroversion"), source_microversion, obj, QString("QString"));
    }

    return obj;
}

QList<OAIBTMConfigurationParameter-819*>*
OAIBTConfigurationResponse-2019::getConfigurationParameters() {
    return configuration_parameters;
}
void
OAIBTConfigurationResponse-2019::setConfigurationParameters(QList<OAIBTMConfigurationParameter-819*>* configuration_parameters) {
    this->configuration_parameters = configuration_parameters;
    this->m_configuration_parameters_isSet = true;
}

QList<OAIBTMParameter-1*>*
OAIBTConfigurationResponse-2019::getCurrentConfiguration() {
    return current_configuration;
}
void
OAIBTConfigurationResponse-2019::setCurrentConfiguration(QList<OAIBTMParameter-1*>* current_configuration) {
    this->current_configuration = current_configuration;
    this->m_current_configuration_isSet = true;
}

qint32
OAIBTConfigurationResponse-2019::getLibraryVersion() {
    return library_version;
}
void
OAIBTConfigurationResponse-2019::setLibraryVersion(qint32 library_version) {
    this->library_version = library_version;
    this->m_library_version_isSet = true;
}

bool
OAIBTConfigurationResponse-2019::isMicroversionSkew() {
    return microversion_skew;
}
void
OAIBTConfigurationResponse-2019::setMicroversionSkew(bool microversion_skew) {
    this->microversion_skew = microversion_skew;
    this->m_microversion_skew_isSet = true;
}

bool
OAIBTConfigurationResponse-2019::isRejectMicroversionSkew() {
    return reject_microversion_skew;
}
void
OAIBTConfigurationResponse-2019::setRejectMicroversionSkew(bool reject_microversion_skew) {
    this->reject_microversion_skew = reject_microversion_skew;
    this->m_reject_microversion_skew_isSet = true;
}

QString*
OAIBTConfigurationResponse-2019::getSerializationVersion() {
    return serialization_version;
}
void
OAIBTConfigurationResponse-2019::setSerializationVersion(QString* serialization_version) {
    this->serialization_version = serialization_version;
    this->m_serialization_version_isSet = true;
}

QString*
OAIBTConfigurationResponse-2019::getSourceMicroversion() {
    return source_microversion;
}
void
OAIBTConfigurationResponse-2019::setSourceMicroversion(QString* source_microversion) {
    this->source_microversion = source_microversion;
    this->m_source_microversion_isSet = true;
}


bool
OAIBTConfigurationResponse-2019::isSet(){
    bool isObjectUpdated = false;
    do{
        if(configuration_parameters->size() > 0){ isObjectUpdated = true; break;}
        if(current_configuration->size() > 0){ isObjectUpdated = true; break;}
        if(m_library_version_isSet){ isObjectUpdated = true; break;}
        if(m_microversion_skew_isSet){ isObjectUpdated = true; break;}
        if(m_reject_microversion_skew_isSet){ isObjectUpdated = true; break;}
        if(serialization_version != nullptr && *serialization_version != QString("")){ isObjectUpdated = true; break;}
        if(source_microversion != nullptr && *source_microversion != QString("")){ isObjectUpdated = true; break;}
    }while(false);
    return isObjectUpdated;
}
}

