/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.111
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIBTTableCell-1114.h
 *
 * 
 */

#ifndef OAIBTTableCell-1114_H_
#define OAIBTTableCell-1114_H_

#include <QJsonObject>


#include <QString>

#include "OAIObject.h"

namespace OpenAPI {

class OAIBTTableCell-1114: public OAIObject {
public:
    OAIBTTableCell-1114();
    OAIBTTableCell-1114(QString json);
    ~OAIBTTableCell-1114();
    void init();
    void cleanup();

    QString asJson () override;
    QJsonObject asJsonObject() override;
    void fromJsonObject(QJsonObject json) override;
    OAIBTTableCell-1114* fromJson(QString jsonString) override;

    QString* getBtType();
    void setBtType(QString* bt_type);

    bool isIsEverVisible();
    void setIsEverVisible(bool is_ever_visible);

    bool isIsReadOnly();
    void setIsReadOnly(bool is_read_only);


    virtual bool isSet() override;

private:
    QString* bt_type;
    bool m_bt_type_isSet;

    bool is_ever_visible;
    bool m_is_ever_visible_isSet;

    bool is_read_only;
    bool m_is_read_only_isSet;

};

}

#endif /* OAIBTTableCell-1114_H_ */
