/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.111
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIBTWorkflowStateInfo.h
 *
 * 
 */

#ifndef OAIBTWorkflowStateInfo_H_
#define OAIBTWorkflowStateInfo_H_

#include <QJsonObject>


#include <QList>
#include <QString>

#include "OAIObject.h"

namespace OpenAPI {

class OAIBTWorkflowStateInfo: public OAIObject {
public:
    OAIBTWorkflowStateInfo();
    OAIBTWorkflowStateInfo(QString json);
    ~OAIBTWorkflowStateInfo();
    void init();
    void cleanup();

    QString asJson () override;
    QJsonObject asJsonObject() override;
    void fromJsonObject(QJsonObject json) override;
    OAIBTWorkflowStateInfo* fromJson(QString jsonString) override;

    QString* getApproverSourceProperty();
    void setApproverSourceProperty(QString* approver_source_property);

    QString* getDisplayName();
    void setDisplayName(QString* display_name);

    QList<QString*>* getEditableProperties();
    void setEditableProperties(QList<QString*>* editable_properties);

    QString* getName();
    void setName(QString* name);

    QString* getNotifierSourceProperty();
    void setNotifierSourceProperty(QString* notifier_source_property);

    QList<QString*>* getRequiredItemProperties();
    void setRequiredItemProperties(QList<QString*>* required_item_properties);

    QList<QString*>* getRequiredProperties();
    void setRequiredProperties(QList<QString*>* required_properties);


    virtual bool isSet() override;

private:
    QString* approver_source_property;
    bool m_approver_source_property_isSet;

    QString* display_name;
    bool m_display_name_isSet;

    QList<QString*>* editable_properties;
    bool m_editable_properties_isSet;

    QString* name;
    bool m_name_isSet;

    QString* notifier_source_property;
    bool m_notifier_source_property_isSet;

    QList<QString*>* required_item_properties;
    bool m_required_item_properties_isSet;

    QList<QString*>* required_properties;
    bool m_required_properties_isSet;

};

}

#endif /* OAIBTWorkflowStateInfo_H_ */
