/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.111
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIBTAssemblyFeatureInfo.h
 *
 * 
 */

#ifndef OAIBTAssemblyFeatureInfo_H_
#define OAIBTAssemblyFeatureInfo_H_

#include <QJsonObject>


#include "OAIBTAssemblyFeatureDataInfo.h"
#include <QString>

#include "OAIObject.h"

namespace OpenAPI {

class OAIBTAssemblyFeatureInfo: public OAIObject {
public:
    OAIBTAssemblyFeatureInfo();
    OAIBTAssemblyFeatureInfo(QString json);
    ~OAIBTAssemblyFeatureInfo();
    void init();
    void cleanup();

    QString asJson () override;
    QJsonObject asJsonObject() override;
    void fromJsonObject(QJsonObject json) override;
    OAIBTAssemblyFeatureInfo* fromJson(QString jsonString) override;

    OAIBTAssemblyFeatureDataInfo* getFeatureData();
    void setFeatureData(OAIBTAssemblyFeatureDataInfo* feature_data);

    QString* getFeatureType();
    void setFeatureType(QString* feature_type);

    QString* getId();
    void setId(QString* id);

    bool isSuppressed();
    void setSuppressed(bool suppressed);


    virtual bool isSet() override;

private:
    OAIBTAssemblyFeatureDataInfo* feature_data;
    bool m_feature_data_isSet;

    QString* feature_type;
    bool m_feature_type_isSet;

    QString* id;
    bool m_id_isSet;

    bool suppressed;
    bool m_suppressed_isSet;

};

}

#endif /* OAIBTAssemblyFeatureInfo_H_ */
