/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.111
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIBTPartMaterial-1445.h
 *
 * 
 */

#ifndef OAIBTPartMaterial-1445_H_
#define OAIBTPartMaterial-1445_H_

#include <QJsonObject>


#include "OAIBTElementReference-725.h"
#include "OAIBTPartMaterialProperty-1453.h"
#include <QList>
#include <QMap>
#include <QString>

#include "OAIObject.h"

namespace OpenAPI {

class OAIBTPartMaterial-1445: public OAIObject {
public:
    OAIBTPartMaterial-1445();
    OAIBTPartMaterial-1445(QString json);
    ~OAIBTPartMaterial-1445();
    void init();
    void cleanup();

    QString asJson () override;
    QJsonObject asJsonObject() override;
    void fromJsonObject(QJsonObject json) override;
    OAIBTPartMaterial-1445* fromJson(QString jsonString) override;

    QString* getBtType();
    void setBtType(QString* bt_type);

    QString* getId();
    void setId(QString* id);

    QString* getLibraryName();
    void setLibraryName(QString* library_name);

    OAIBTElementReference-725* getLibraryReference();
    void setLibraryReference(OAIBTElementReference-725* library_reference);

    QString* getName();
    void setName(QString* name);

    QMap<QString, OAIBTPartMaterialProperty-1453*>* getProperties();
    void setProperties(QMap<QString, OAIBTPartMaterialProperty-1453*>* properties);

    qint32 getVersion();
    void setVersion(qint32 version);


    virtual bool isSet() override;

private:
    QString* bt_type;
    bool m_bt_type_isSet;

    QString* id;
    bool m_id_isSet;

    QString* library_name;
    bool m_library_name_isSet;

    OAIBTElementReference-725* library_reference;
    bool m_library_reference_isSet;

    QString* name;
    bool m_name_isSet;

    QMap<QString, OAIBTPartMaterialProperty-1453*>* properties;
    bool m_properties_isSet;

    qint32 version;
    bool m_version_isSet;

};

}

#endif /* OAIBTPartMaterial-1445_H_ */
