/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.111
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


#include "OAIBTSettingInfo.h"

#include "OAIHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace OpenAPI {

OAIBTSettingInfo::OAIBTSettingInfo(QString json) {
    init();
    this->fromJson(json);
}

OAIBTSettingInfo::OAIBTSettingInfo() {
    init();
}

OAIBTSettingInfo::~OAIBTSettingInfo() {
    this->cleanup();
}

void
OAIBTSettingInfo::init() {
    key = new QString("");
    m_key_isSet = false;
    value = NULL;
    m_value_isSet = false;
}

void
OAIBTSettingInfo::cleanup() {
    if(key != nullptr) { 
        delete key;
    }
    if(value != nullptr) { 
        delete value;
    }
}

OAIBTSettingInfo*
OAIBTSettingInfo::fromJson(QString json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
OAIBTSettingInfo::fromJsonObject(QJsonObject pJson) {
    ::OpenAPI::setValue(&key, pJson["key"], "QString", "QString");
    
    ::OpenAPI::setValue(&value, pJson["value"], "OAIObject", "OAIObject");
    
}

QString
OAIBTSettingInfo::asJson ()
{
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject
OAIBTSettingInfo::asJsonObject() {
    QJsonObject obj;
    if(key != nullptr && *key != QString("")){
        toJsonValue(QString("key"), key, obj, QString("QString"));
    }
    if((value != nullptr) && (value->isSet())){
        toJsonValue(QString("value"), value, obj, QString("OAIObject"));
    }

    return obj;
}

QString*
OAIBTSettingInfo::getKey() {
    return key;
}
void
OAIBTSettingInfo::setKey(QString* key) {
    this->key = key;
    this->m_key_isSet = true;
}

OAIObject*
OAIBTSettingInfo::getValue() {
    return value;
}
void
OAIBTSettingInfo::setValue(OAIObject* value) {
    this->value = value;
    this->m_value_isSet = true;
}


bool
OAIBTSettingInfo::isSet(){
    bool isObjectUpdated = false;
    do{
        if(key != nullptr && *key != QString("")){ isObjectUpdated = true; break;}
        if(value != nullptr && value->isSet()){ isObjectUpdated = true; break;}
    }while(false);
    return isObjectUpdated;
}
}

