/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.111
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIBTFeatureDefinitionResponse-1617.h
 *
 * 
 */

#ifndef OAIBTFeatureDefinitionResponse-1617_H_
#define OAIBTFeatureDefinitionResponse-1617_H_

#include <QJsonObject>


#include "OAIBTFeatureApiBase-1430.h"
#include "OAIBTFeatureState-1688.h"
#include "OAIBTMFeature-134.h"
#include <QString>

#include "OAIObject.h"

namespace OpenAPI {

class OAIBTFeatureDefinitionResponse-1617: public OAIObject {
public:
    OAIBTFeatureDefinitionResponse-1617();
    OAIBTFeatureDefinitionResponse-1617(QString json);
    ~OAIBTFeatureDefinitionResponse-1617();
    void init();
    void cleanup();

    QString asJson () override;
    QJsonObject asJsonObject() override;
    void fromJsonObject(QJsonObject json) override;
    OAIBTFeatureDefinitionResponse-1617* fromJson(QString jsonString) override;

    QString* getBtType();
    void setBtType(QString* bt_type);

    qint32 getLibraryVersion();
    void setLibraryVersion(qint32 library_version);

    bool isMicroversionSkew();
    void setMicroversionSkew(bool microversion_skew);

    bool isRejectMicroversionSkew();
    void setRejectMicroversionSkew(bool reject_microversion_skew);

    QString* getSerializationVersion();
    void setSerializationVersion(QString* serialization_version);

    QString* getSourceMicroversion();
    void setSourceMicroversion(QString* source_microversion);

    OAIBTFeatureState-1688* getFeatureState();
    void setFeatureState(OAIBTFeatureState-1688* feature_state);

    OAIBTMFeature-134* getFeature();
    void setFeature(OAIBTMFeature-134* feature);


    virtual bool isSet() override;

private:
    QString* bt_type;
    bool m_bt_type_isSet;

    qint32 library_version;
    bool m_library_version_isSet;

    bool microversion_skew;
    bool m_microversion_skew_isSet;

    bool reject_microversion_skew;
    bool m_reject_microversion_skew_isSet;

    QString* serialization_version;
    bool m_serialization_version_isSet;

    QString* source_microversion;
    bool m_source_microversion_isSet;

    OAIBTFeatureState-1688* feature_state;
    bool m_feature_state_isSet;

    OAIBTMFeature-134* feature;
    bool m_feature_isSet;

};

}

#endif /* OAIBTFeatureDefinitionResponse-1617_H_ */
