/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.111
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


#include "OAIBTPExpressionFunction-1325.h"

#include "OAIHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace OpenAPI {

OAIBTPExpressionFunction-1325::OAIBTPExpressionFunction-1325(QString json) {
    init();
    this->fromJson(json);
}

OAIBTPExpressionFunction-1325::OAIBTPExpressionFunction-1325() {
    init();
}

OAIBTPExpressionFunction-1325::~OAIBTPExpressionFunction-1325() {
    this->cleanup();
}

void
OAIBTPExpressionFunction-1325::init() {
    atomic = false;
    m_atomic_isSet = false;
    bt_type = new QString("");
    m_bt_type_isSet = false;
    documentation_type = new QString("");
    m_documentation_type_isSet = false;
    end_source_location = 0;
    m_end_source_location_isSet = false;
    node_id = new QString("");
    m_node_id_isSet = false;
    short_descriptor = new QString("");
    m_short_descriptor_isSet = false;
    space_after = new OAIBTPSpace-10();
    m_space_after_isSet = false;
    space_before = new OAIBTPSpace-10();
    m_space_before_isSet = false;
    space_default = false;
    m_space_default_isSet = false;
    start_source_location = 0;
    m_start_source_location_isSet = false;
    body = new OAIBTPStatementBlock-271();
    m_body_isSet = false;
    arguments = new QList<OAIBTPArgumentDeclaration-232*>();
    m_arguments_isSet = false;
    space_after_function = new OAIBTPSpace-10();
    m_space_after_function_isSet = false;
    precondition = new OAIBTPStatement-269();
    m_precondition_isSet = false;
    space_after_arglist = new OAIBTPSpace-10();
    m_space_after_arglist_isSet = false;
    space_in_empty_list = new OAIBTPSpace-10();
    m_space_in_empty_list_isSet = false;
    return_type = new OAIBTPTypeName-290();
    m_return_type_isSet = false;
}

void
OAIBTPExpressionFunction-1325::cleanup() {

    if(bt_type != nullptr) { 
        delete bt_type;
    }
    if(documentation_type != nullptr) { 
        delete documentation_type;
    }

    if(node_id != nullptr) { 
        delete node_id;
    }
    if(short_descriptor != nullptr) { 
        delete short_descriptor;
    }
    if(space_after != nullptr) { 
        delete space_after;
    }
    if(space_before != nullptr) { 
        delete space_before;
    }


    if(body != nullptr) { 
        delete body;
    }
    if(arguments != nullptr) { 
        auto arr = arguments;
        for(auto o: *arr) { 
            delete o;
        }
        delete arguments;
    }
    if(space_after_function != nullptr) { 
        delete space_after_function;
    }
    if(precondition != nullptr) { 
        delete precondition;
    }
    if(space_after_arglist != nullptr) { 
        delete space_after_arglist;
    }
    if(space_in_empty_list != nullptr) { 
        delete space_in_empty_list;
    }
    if(return_type != nullptr) { 
        delete return_type;
    }
}

OAIBTPExpressionFunction-1325*
OAIBTPExpressionFunction-1325::fromJson(QString json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
OAIBTPExpressionFunction-1325::fromJsonObject(QJsonObject pJson) {
    ::OpenAPI::setValue(&atomic, pJson["atomic"], "bool", "");
    
    ::OpenAPI::setValue(&bt_type, pJson["btType"], "QString", "QString");
    
    ::OpenAPI::setValue(&documentation_type, pJson["documentationType"], "QString", "QString");
    
    ::OpenAPI::setValue(&end_source_location, pJson["endSourceLocation"], "qint32", "");
    
    ::OpenAPI::setValue(&node_id, pJson["nodeId"], "QString", "QString");
    
    ::OpenAPI::setValue(&short_descriptor, pJson["shortDescriptor"], "QString", "QString");
    
    ::OpenAPI::setValue(&space_after, pJson["spaceAfter"], "OAIBTPSpace-10", "OAIBTPSpace-10");
    
    ::OpenAPI::setValue(&space_before, pJson["spaceBefore"], "OAIBTPSpace-10", "OAIBTPSpace-10");
    
    ::OpenAPI::setValue(&space_default, pJson["spaceDefault"], "bool", "");
    
    ::OpenAPI::setValue(&start_source_location, pJson["startSourceLocation"], "qint32", "");
    
    ::OpenAPI::setValue(&body, pJson["body"], "OAIBTPStatementBlock-271", "OAIBTPStatementBlock-271");
    
    
    ::OpenAPI::setValue(&arguments, pJson["arguments"], "QList", "OAIBTPArgumentDeclaration-232");
    ::OpenAPI::setValue(&space_after_function, pJson["spaceAfterFunction"], "OAIBTPSpace-10", "OAIBTPSpace-10");
    
    ::OpenAPI::setValue(&precondition, pJson["precondition"], "OAIBTPStatement-269", "OAIBTPStatement-269");
    
    ::OpenAPI::setValue(&space_after_arglist, pJson["spaceAfterArglist"], "OAIBTPSpace-10", "OAIBTPSpace-10");
    
    ::OpenAPI::setValue(&space_in_empty_list, pJson["spaceInEmptyList"], "OAIBTPSpace-10", "OAIBTPSpace-10");
    
    ::OpenAPI::setValue(&return_type, pJson["returnType"], "OAIBTPTypeName-290", "OAIBTPTypeName-290");
    
}

QString
OAIBTPExpressionFunction-1325::asJson ()
{
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject
OAIBTPExpressionFunction-1325::asJsonObject() {
    QJsonObject obj;
    if(m_atomic_isSet){
        obj.insert("atomic", QJsonValue(atomic));
    }
    if(bt_type != nullptr && *bt_type != QString("")){
        toJsonValue(QString("btType"), bt_type, obj, QString("QString"));
    }
    if(documentation_type != nullptr && *documentation_type != QString("")){
        toJsonValue(QString("documentationType"), documentation_type, obj, QString("QString"));
    }
    if(m_end_source_location_isSet){
        obj.insert("endSourceLocation", QJsonValue(end_source_location));
    }
    if(node_id != nullptr && *node_id != QString("")){
        toJsonValue(QString("nodeId"), node_id, obj, QString("QString"));
    }
    if(short_descriptor != nullptr && *short_descriptor != QString("")){
        toJsonValue(QString("shortDescriptor"), short_descriptor, obj, QString("QString"));
    }
    if((space_after != nullptr) && (space_after->isSet())){
        toJsonValue(QString("spaceAfter"), space_after, obj, QString("OAIBTPSpace-10"));
    }
    if((space_before != nullptr) && (space_before->isSet())){
        toJsonValue(QString("spaceBefore"), space_before, obj, QString("OAIBTPSpace-10"));
    }
    if(m_space_default_isSet){
        obj.insert("spaceDefault", QJsonValue(space_default));
    }
    if(m_start_source_location_isSet){
        obj.insert("startSourceLocation", QJsonValue(start_source_location));
    }
    if((body != nullptr) && (body->isSet())){
        toJsonValue(QString("body"), body, obj, QString("OAIBTPStatementBlock-271"));
    }
    if(arguments->size() > 0){
        toJsonArray((QList<void*>*)arguments, obj, "arguments", "OAIBTPArgumentDeclaration-232");
    }
    if((space_after_function != nullptr) && (space_after_function->isSet())){
        toJsonValue(QString("spaceAfterFunction"), space_after_function, obj, QString("OAIBTPSpace-10"));
    }
    if((precondition != nullptr) && (precondition->isSet())){
        toJsonValue(QString("precondition"), precondition, obj, QString("OAIBTPStatement-269"));
    }
    if((space_after_arglist != nullptr) && (space_after_arglist->isSet())){
        toJsonValue(QString("spaceAfterArglist"), space_after_arglist, obj, QString("OAIBTPSpace-10"));
    }
    if((space_in_empty_list != nullptr) && (space_in_empty_list->isSet())){
        toJsonValue(QString("spaceInEmptyList"), space_in_empty_list, obj, QString("OAIBTPSpace-10"));
    }
    if((return_type != nullptr) && (return_type->isSet())){
        toJsonValue(QString("returnType"), return_type, obj, QString("OAIBTPTypeName-290"));
    }

    return obj;
}

bool
OAIBTPExpressionFunction-1325::isAtomic() {
    return atomic;
}
void
OAIBTPExpressionFunction-1325::setAtomic(bool atomic) {
    this->atomic = atomic;
    this->m_atomic_isSet = true;
}

QString*
OAIBTPExpressionFunction-1325::getBtType() {
    return bt_type;
}
void
OAIBTPExpressionFunction-1325::setBtType(QString* bt_type) {
    this->bt_type = bt_type;
    this->m_bt_type_isSet = true;
}

QString*
OAIBTPExpressionFunction-1325::getDocumentationType() {
    return documentation_type;
}
void
OAIBTPExpressionFunction-1325::setDocumentationType(QString* documentation_type) {
    this->documentation_type = documentation_type;
    this->m_documentation_type_isSet = true;
}

qint32
OAIBTPExpressionFunction-1325::getEndSourceLocation() {
    return end_source_location;
}
void
OAIBTPExpressionFunction-1325::setEndSourceLocation(qint32 end_source_location) {
    this->end_source_location = end_source_location;
    this->m_end_source_location_isSet = true;
}

QString*
OAIBTPExpressionFunction-1325::getNodeId() {
    return node_id;
}
void
OAIBTPExpressionFunction-1325::setNodeId(QString* node_id) {
    this->node_id = node_id;
    this->m_node_id_isSet = true;
}

QString*
OAIBTPExpressionFunction-1325::getShortDescriptor() {
    return short_descriptor;
}
void
OAIBTPExpressionFunction-1325::setShortDescriptor(QString* short_descriptor) {
    this->short_descriptor = short_descriptor;
    this->m_short_descriptor_isSet = true;
}

OAIBTPSpace-10*
OAIBTPExpressionFunction-1325::getSpaceAfter() {
    return space_after;
}
void
OAIBTPExpressionFunction-1325::setSpaceAfter(OAIBTPSpace-10* space_after) {
    this->space_after = space_after;
    this->m_space_after_isSet = true;
}

OAIBTPSpace-10*
OAIBTPExpressionFunction-1325::getSpaceBefore() {
    return space_before;
}
void
OAIBTPExpressionFunction-1325::setSpaceBefore(OAIBTPSpace-10* space_before) {
    this->space_before = space_before;
    this->m_space_before_isSet = true;
}

bool
OAIBTPExpressionFunction-1325::isSpaceDefault() {
    return space_default;
}
void
OAIBTPExpressionFunction-1325::setSpaceDefault(bool space_default) {
    this->space_default = space_default;
    this->m_space_default_isSet = true;
}

qint32
OAIBTPExpressionFunction-1325::getStartSourceLocation() {
    return start_source_location;
}
void
OAIBTPExpressionFunction-1325::setStartSourceLocation(qint32 start_source_location) {
    this->start_source_location = start_source_location;
    this->m_start_source_location_isSet = true;
}

OAIBTPStatementBlock-271*
OAIBTPExpressionFunction-1325::getBody() {
    return body;
}
void
OAIBTPExpressionFunction-1325::setBody(OAIBTPStatementBlock-271* body) {
    this->body = body;
    this->m_body_isSet = true;
}

QList<OAIBTPArgumentDeclaration-232*>*
OAIBTPExpressionFunction-1325::getArguments() {
    return arguments;
}
void
OAIBTPExpressionFunction-1325::setArguments(QList<OAIBTPArgumentDeclaration-232*>* arguments) {
    this->arguments = arguments;
    this->m_arguments_isSet = true;
}

OAIBTPSpace-10*
OAIBTPExpressionFunction-1325::getSpaceAfterFunction() {
    return space_after_function;
}
void
OAIBTPExpressionFunction-1325::setSpaceAfterFunction(OAIBTPSpace-10* space_after_function) {
    this->space_after_function = space_after_function;
    this->m_space_after_function_isSet = true;
}

OAIBTPStatement-269*
OAIBTPExpressionFunction-1325::getPrecondition() {
    return precondition;
}
void
OAIBTPExpressionFunction-1325::setPrecondition(OAIBTPStatement-269* precondition) {
    this->precondition = precondition;
    this->m_precondition_isSet = true;
}

OAIBTPSpace-10*
OAIBTPExpressionFunction-1325::getSpaceAfterArglist() {
    return space_after_arglist;
}
void
OAIBTPExpressionFunction-1325::setSpaceAfterArglist(OAIBTPSpace-10* space_after_arglist) {
    this->space_after_arglist = space_after_arglist;
    this->m_space_after_arglist_isSet = true;
}

OAIBTPSpace-10*
OAIBTPExpressionFunction-1325::getSpaceInEmptyList() {
    return space_in_empty_list;
}
void
OAIBTPExpressionFunction-1325::setSpaceInEmptyList(OAIBTPSpace-10* space_in_empty_list) {
    this->space_in_empty_list = space_in_empty_list;
    this->m_space_in_empty_list_isSet = true;
}

OAIBTPTypeName-290*
OAIBTPExpressionFunction-1325::getReturnType() {
    return return_type;
}
void
OAIBTPExpressionFunction-1325::setReturnType(OAIBTPTypeName-290* return_type) {
    this->return_type = return_type;
    this->m_return_type_isSet = true;
}


bool
OAIBTPExpressionFunction-1325::isSet(){
    bool isObjectUpdated = false;
    do{
        if(m_atomic_isSet){ isObjectUpdated = true; break;}
        if(bt_type != nullptr && *bt_type != QString("")){ isObjectUpdated = true; break;}
        if(documentation_type != nullptr && *documentation_type != QString("")){ isObjectUpdated = true; break;}
        if(m_end_source_location_isSet){ isObjectUpdated = true; break;}
        if(node_id != nullptr && *node_id != QString("")){ isObjectUpdated = true; break;}
        if(short_descriptor != nullptr && *short_descriptor != QString("")){ isObjectUpdated = true; break;}
        if(space_after != nullptr && space_after->isSet()){ isObjectUpdated = true; break;}
        if(space_before != nullptr && space_before->isSet()){ isObjectUpdated = true; break;}
        if(m_space_default_isSet){ isObjectUpdated = true; break;}
        if(m_start_source_location_isSet){ isObjectUpdated = true; break;}
        if(body != nullptr && body->isSet()){ isObjectUpdated = true; break;}
        if(arguments->size() > 0){ isObjectUpdated = true; break;}
        if(space_after_function != nullptr && space_after_function->isSet()){ isObjectUpdated = true; break;}
        if(precondition != nullptr && precondition->isSet()){ isObjectUpdated = true; break;}
        if(space_after_arglist != nullptr && space_after_arglist->isSet()){ isObjectUpdated = true; break;}
        if(space_in_empty_list != nullptr && space_in_empty_list->isSet()){ isObjectUpdated = true; break;}
        if(return_type != nullptr && return_type->isSet()){ isObjectUpdated = true; break;}
    }while(false);
    return isObjectUpdated;
}
}

