/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.111
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIBTPlaneDescription-692.h
 *
 * 
 */

#ifndef OAIBTPlaneDescription-692_H_
#define OAIBTPlaneDescription-692_H_

#include <QJsonObject>


#include "OAIBTSurfaceDescription-1564.h"
#include "OAIBTVector3d-389.h"
#include <QString>

#include "OAIObject.h"

namespace OpenAPI {

class OAIBTPlaneDescription-692: public OAIObject {
public:
    OAIBTPlaneDescription-692();
    OAIBTPlaneDescription-692(QString json);
    ~OAIBTPlaneDescription-692();
    void init();
    void cleanup();

    QString asJson () override;
    QJsonObject asJsonObject() override;
    void fromJsonObject(QJsonObject json) override;
    OAIBTPlaneDescription-692* fromJson(QString jsonString) override;

    QString* getBtType();
    void setBtType(QString* bt_type);

    QString* getType();
    void setType(QString* type);

    OAIBTVector3d-389* getNormal();
    void setNormal(OAIBTVector3d-389* normal);

    bool isIsOrientedWithFace();
    void setIsOrientedWithFace(bool is_oriented_with_face);

    OAIBTVector3d-389* getOrigin();
    void setOrigin(OAIBTVector3d-389* origin);


    virtual bool isSet() override;

private:
    QString* bt_type;
    bool m_bt_type_isSet;

    QString* type;
    bool m_type_isSet;

    OAIBTVector3d-389* normal;
    bool m_normal_isSet;

    bool is_oriented_with_face;
    bool m_is_oriented_with_face_isSet;

    OAIBTVector3d-389* origin;
    bool m_origin_isSet;

};

}

#endif /* OAIBTPlaneDescription-692_H_ */
