/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.111
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


#include "OAIBTUserSummaryInfo.h"

#include "OAIHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace OpenAPI {

OAIBTUserSummaryInfo::OAIBTUserSummaryInfo(QString json) {
    init();
    this->fromJson(json);
}

OAIBTUserSummaryInfo::OAIBTUserSummaryInfo() {
    init();
}

OAIBTUserSummaryInfo::~OAIBTUserSummaryInfo() {
    this->cleanup();
}

void
OAIBTUserSummaryInfo::init() {
    company = new OAIBTCompanySummaryInfo();
    m_company_isSet = false;
    email = new QString("");
    m_email_isSet = false;
    first_name = new QString("");
    m_first_name_isSet = false;
    global_permissions = new OAIGlobalPermissionInfo();
    m_global_permissions_isSet = false;
    href = new QString("");
    m_href_isSet = false;
    id = new QString("");
    m_id_isSet = false;
    image = new QString("");
    m_image_isSet = false;
    is_guest = false;
    m_is_guest_isSet = false;
    is_light = false;
    m_is_light_isSet = false;
    last_login_time = NULL;
    m_last_login_time_isSet = false;
    last_name = new QString("");
    m_last_name_isSet = false;
    name = new QString("");
    m_name_isSet = false;
    source = 0;
    m_source_isSet = false;
    state = 0;
    m_state_isSet = false;
    view_ref = new QString("");
    m_view_ref_isSet = false;
}

void
OAIBTUserSummaryInfo::cleanup() {
    if(company != nullptr) { 
        delete company;
    }
    if(email != nullptr) { 
        delete email;
    }
    if(first_name != nullptr) { 
        delete first_name;
    }
    if(global_permissions != nullptr) { 
        delete global_permissions;
    }
    if(href != nullptr) { 
        delete href;
    }
    if(id != nullptr) { 
        delete id;
    }
    if(image != nullptr) { 
        delete image;
    }


    if(last_login_time != nullptr) { 
        delete last_login_time;
    }
    if(last_name != nullptr) { 
        delete last_name;
    }
    if(name != nullptr) { 
        delete name;
    }


    if(view_ref != nullptr) { 
        delete view_ref;
    }
}

OAIBTUserSummaryInfo*
OAIBTUserSummaryInfo::fromJson(QString json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
OAIBTUserSummaryInfo::fromJsonObject(QJsonObject pJson) {
    ::OpenAPI::setValue(&company, pJson["company"], "OAIBTCompanySummaryInfo", "OAIBTCompanySummaryInfo");
    
    ::OpenAPI::setValue(&email, pJson["email"], "QString", "QString");
    
    ::OpenAPI::setValue(&first_name, pJson["firstName"], "QString", "QString");
    
    ::OpenAPI::setValue(&global_permissions, pJson["globalPermissions"], "OAIGlobalPermissionInfo", "OAIGlobalPermissionInfo");
    
    ::OpenAPI::setValue(&href, pJson["href"], "QString", "QString");
    
    ::OpenAPI::setValue(&id, pJson["id"], "QString", "QString");
    
    ::OpenAPI::setValue(&image, pJson["image"], "QString", "QString");
    
    ::OpenAPI::setValue(&is_guest, pJson["isGuest"], "bool", "");
    
    ::OpenAPI::setValue(&is_light, pJson["isLight"], "bool", "");
    
    ::OpenAPI::setValue(&last_login_time, pJson["lastLoginTime"], "QDateTime", "QDateTime");
    
    ::OpenAPI::setValue(&last_name, pJson["lastName"], "QString", "QString");
    
    ::OpenAPI::setValue(&name, pJson["name"], "QString", "QString");
    
    ::OpenAPI::setValue(&source, pJson["source"], "qint32", "");
    
    ::OpenAPI::setValue(&state, pJson["state"], "qint32", "");
    
    ::OpenAPI::setValue(&view_ref, pJson["viewRef"], "QString", "QString");
    
}

QString
OAIBTUserSummaryInfo::asJson ()
{
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject
OAIBTUserSummaryInfo::asJsonObject() {
    QJsonObject obj;
    if((company != nullptr) && (company->isSet())){
        toJsonValue(QString("company"), company, obj, QString("OAIBTCompanySummaryInfo"));
    }
    if(email != nullptr && *email != QString("")){
        toJsonValue(QString("email"), email, obj, QString("QString"));
    }
    if(first_name != nullptr && *first_name != QString("")){
        toJsonValue(QString("firstName"), first_name, obj, QString("QString"));
    }
    if((global_permissions != nullptr) && (global_permissions->isSet())){
        toJsonValue(QString("globalPermissions"), global_permissions, obj, QString("OAIGlobalPermissionInfo"));
    }
    if(href != nullptr && *href != QString("")){
        toJsonValue(QString("href"), href, obj, QString("QString"));
    }
    if(id != nullptr && *id != QString("")){
        toJsonValue(QString("id"), id, obj, QString("QString"));
    }
    if(image != nullptr && *image != QString("")){
        toJsonValue(QString("image"), image, obj, QString("QString"));
    }
    if(m_is_guest_isSet){
        obj.insert("isGuest", QJsonValue(is_guest));
    }
    if(m_is_light_isSet){
        obj.insert("isLight", QJsonValue(is_light));
    }
    if(last_login_time != nullptr) { 
        toJsonValue(QString("lastLoginTime"), last_login_time, obj, QString("QDateTime"));
    }
    if(last_name != nullptr && *last_name != QString("")){
        toJsonValue(QString("lastName"), last_name, obj, QString("QString"));
    }
    if(name != nullptr && *name != QString("")){
        toJsonValue(QString("name"), name, obj, QString("QString"));
    }
    if(m_source_isSet){
        obj.insert("source", QJsonValue(source));
    }
    if(m_state_isSet){
        obj.insert("state", QJsonValue(state));
    }
    if(view_ref != nullptr && *view_ref != QString("")){
        toJsonValue(QString("viewRef"), view_ref, obj, QString("QString"));
    }

    return obj;
}

OAIBTCompanySummaryInfo*
OAIBTUserSummaryInfo::getCompany() {
    return company;
}
void
OAIBTUserSummaryInfo::setCompany(OAIBTCompanySummaryInfo* company) {
    this->company = company;
    this->m_company_isSet = true;
}

QString*
OAIBTUserSummaryInfo::getEmail() {
    return email;
}
void
OAIBTUserSummaryInfo::setEmail(QString* email) {
    this->email = email;
    this->m_email_isSet = true;
}

QString*
OAIBTUserSummaryInfo::getFirstName() {
    return first_name;
}
void
OAIBTUserSummaryInfo::setFirstName(QString* first_name) {
    this->first_name = first_name;
    this->m_first_name_isSet = true;
}

OAIGlobalPermissionInfo*
OAIBTUserSummaryInfo::getGlobalPermissions() {
    return global_permissions;
}
void
OAIBTUserSummaryInfo::setGlobalPermissions(OAIGlobalPermissionInfo* global_permissions) {
    this->global_permissions = global_permissions;
    this->m_global_permissions_isSet = true;
}

QString*
OAIBTUserSummaryInfo::getHref() {
    return href;
}
void
OAIBTUserSummaryInfo::setHref(QString* href) {
    this->href = href;
    this->m_href_isSet = true;
}

QString*
OAIBTUserSummaryInfo::getId() {
    return id;
}
void
OAIBTUserSummaryInfo::setId(QString* id) {
    this->id = id;
    this->m_id_isSet = true;
}

QString*
OAIBTUserSummaryInfo::getImage() {
    return image;
}
void
OAIBTUserSummaryInfo::setImage(QString* image) {
    this->image = image;
    this->m_image_isSet = true;
}

bool
OAIBTUserSummaryInfo::isIsGuest() {
    return is_guest;
}
void
OAIBTUserSummaryInfo::setIsGuest(bool is_guest) {
    this->is_guest = is_guest;
    this->m_is_guest_isSet = true;
}

bool
OAIBTUserSummaryInfo::isIsLight() {
    return is_light;
}
void
OAIBTUserSummaryInfo::setIsLight(bool is_light) {
    this->is_light = is_light;
    this->m_is_light_isSet = true;
}

QDateTime*
OAIBTUserSummaryInfo::getLastLoginTime() {
    return last_login_time;
}
void
OAIBTUserSummaryInfo::setLastLoginTime(QDateTime* last_login_time) {
    this->last_login_time = last_login_time;
    this->m_last_login_time_isSet = true;
}

QString*
OAIBTUserSummaryInfo::getLastName() {
    return last_name;
}
void
OAIBTUserSummaryInfo::setLastName(QString* last_name) {
    this->last_name = last_name;
    this->m_last_name_isSet = true;
}

QString*
OAIBTUserSummaryInfo::getName() {
    return name;
}
void
OAIBTUserSummaryInfo::setName(QString* name) {
    this->name = name;
    this->m_name_isSet = true;
}

qint32
OAIBTUserSummaryInfo::getSource() {
    return source;
}
void
OAIBTUserSummaryInfo::setSource(qint32 source) {
    this->source = source;
    this->m_source_isSet = true;
}

qint32
OAIBTUserSummaryInfo::getState() {
    return state;
}
void
OAIBTUserSummaryInfo::setState(qint32 state) {
    this->state = state;
    this->m_state_isSet = true;
}

QString*
OAIBTUserSummaryInfo::getViewRef() {
    return view_ref;
}
void
OAIBTUserSummaryInfo::setViewRef(QString* view_ref) {
    this->view_ref = view_ref;
    this->m_view_ref_isSet = true;
}


bool
OAIBTUserSummaryInfo::isSet(){
    bool isObjectUpdated = false;
    do{
        if(company != nullptr && company->isSet()){ isObjectUpdated = true; break;}
        if(email != nullptr && *email != QString("")){ isObjectUpdated = true; break;}
        if(first_name != nullptr && *first_name != QString("")){ isObjectUpdated = true; break;}
        if(global_permissions != nullptr && global_permissions->isSet()){ isObjectUpdated = true; break;}
        if(href != nullptr && *href != QString("")){ isObjectUpdated = true; break;}
        if(id != nullptr && *id != QString("")){ isObjectUpdated = true; break;}
        if(image != nullptr && *image != QString("")){ isObjectUpdated = true; break;}
        if(m_is_guest_isSet){ isObjectUpdated = true; break;}
        if(m_is_light_isSet){ isObjectUpdated = true; break;}
        if(last_name != nullptr && *last_name != QString("")){ isObjectUpdated = true; break;}
        if(name != nullptr && *name != QString("")){ isObjectUpdated = true; break;}
        if(m_source_isSet){ isObjectUpdated = true; break;}
        if(m_state_isSet){ isObjectUpdated = true; break;}
        if(view_ref != nullptr && *view_ref != QString("")){ isObjectUpdated = true; break;}
    }while(false);
    return isObjectUpdated;
}
}

