/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.111
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


#include "OAIBTUserOAuth2SummaryInfo.h"

#include "OAIHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace OpenAPI {

OAIBTUserOAuth2SummaryInfo::OAIBTUserOAuth2SummaryInfo(QString json) {
    init();
    this->fromJson(json);
}

OAIBTUserOAuth2SummaryInfo::OAIBTUserOAuth2SummaryInfo() {
    init();
}

OAIBTUserOAuth2SummaryInfo::~OAIBTUserOAuth2SummaryInfo() {
    this->cleanup();
}

void
OAIBTUserOAuth2SummaryInfo::init() {
    client_id = new QString("");
    m_client_id_isSet = false;
    company = new OAIBTCompanySummaryInfo();
    m_company_isSet = false;
    company_plan = false;
    m_company_plan_isSet = false;
    email = new QString("");
    m_email_isSet = false;
    first_name = new QString("");
    m_first_name_isSet = false;
    global_permissions = new OAIGlobalPermissionInfo();
    m_global_permissions_isSet = false;
    href = new QString("");
    m_href_isSet = false;
    id = new QString("");
    m_id_isSet = false;
    image = new QString("");
    m_image_isSet = false;
    is_guest = false;
    m_is_guest_isSet = false;
    is_light = false;
    m_is_light_isSet = false;
    last_login_time = NULL;
    m_last_login_time_isSet = false;
    last_name = new QString("");
    m_last_name_isSet = false;
    name = new QString("");
    m_name_isSet = false;
    oauth2_scopes = 0L;
    m_oauth2_scopes_isSet = false;
    plan_group = new QString("");
    m_plan_group_isSet = false;
    role = 0;
    m_role_isSet = false;
    roles = new QList<RolesEnum*>();
    m_roles_isSet = false;
    source = 0;
    m_source_isSet = false;
    state = 0;
    m_state_isSet = false;
    view_ref = new QString("");
    m_view_ref_isSet = false;
}

void
OAIBTUserOAuth2SummaryInfo::cleanup() {
    if(client_id != nullptr) { 
        delete client_id;
    }
    if(company != nullptr) { 
        delete company;
    }

    if(email != nullptr) { 
        delete email;
    }
    if(first_name != nullptr) { 
        delete first_name;
    }
    if(global_permissions != nullptr) { 
        delete global_permissions;
    }
    if(href != nullptr) { 
        delete href;
    }
    if(id != nullptr) { 
        delete id;
    }
    if(image != nullptr) { 
        delete image;
    }


    if(last_login_time != nullptr) { 
        delete last_login_time;
    }
    if(last_name != nullptr) { 
        delete last_name;
    }
    if(name != nullptr) { 
        delete name;
    }

    if(plan_group != nullptr) { 
        delete plan_group;
    }

    if(roles != nullptr) { 
        auto arr = roles;
        for(auto o: *arr) { 
            delete o;
        }
        delete roles;
    }


    if(view_ref != nullptr) { 
        delete view_ref;
    }
}

OAIBTUserOAuth2SummaryInfo*
OAIBTUserOAuth2SummaryInfo::fromJson(QString json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
OAIBTUserOAuth2SummaryInfo::fromJsonObject(QJsonObject pJson) {
    ::OpenAPI::setValue(&client_id, pJson["clientId"], "QString", "QString");
    
    ::OpenAPI::setValue(&company, pJson["company"], "OAIBTCompanySummaryInfo", "OAIBTCompanySummaryInfo");
    
    ::OpenAPI::setValue(&company_plan, pJson["companyPlan"], "bool", "");
    
    ::OpenAPI::setValue(&email, pJson["email"], "QString", "QString");
    
    ::OpenAPI::setValue(&first_name, pJson["firstName"], "QString", "QString");
    
    ::OpenAPI::setValue(&global_permissions, pJson["globalPermissions"], "OAIGlobalPermissionInfo", "OAIGlobalPermissionInfo");
    
    ::OpenAPI::setValue(&href, pJson["href"], "QString", "QString");
    
    ::OpenAPI::setValue(&id, pJson["id"], "QString", "QString");
    
    ::OpenAPI::setValue(&image, pJson["image"], "QString", "QString");
    
    ::OpenAPI::setValue(&is_guest, pJson["isGuest"], "bool", "");
    
    ::OpenAPI::setValue(&is_light, pJson["isLight"], "bool", "");
    
    ::OpenAPI::setValue(&last_login_time, pJson["lastLoginTime"], "QDateTime", "QDateTime");
    
    ::OpenAPI::setValue(&last_name, pJson["lastName"], "QString", "QString");
    
    ::OpenAPI::setValue(&name, pJson["name"], "QString", "QString");
    
    ::OpenAPI::setValue(&oauth2_scopes, pJson["oauth2Scopes"], "qint64", "");
    
    ::OpenAPI::setValue(&plan_group, pJson["planGroup"], "QString", "QString");
    
    ::OpenAPI::setValue(&role, pJson["role"], "qint32", "");
    
    
    ::OpenAPI::setValue(&roles, pJson["roles"], "QList", "QString");
    ::OpenAPI::setValue(&source, pJson["source"], "qint32", "");
    
    ::OpenAPI::setValue(&state, pJson["state"], "qint32", "");
    
    ::OpenAPI::setValue(&view_ref, pJson["viewRef"], "QString", "QString");
    
}

QString
OAIBTUserOAuth2SummaryInfo::asJson ()
{
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject
OAIBTUserOAuth2SummaryInfo::asJsonObject() {
    QJsonObject obj;
    if(client_id != nullptr && *client_id != QString("")){
        toJsonValue(QString("clientId"), client_id, obj, QString("QString"));
    }
    if((company != nullptr) && (company->isSet())){
        toJsonValue(QString("company"), company, obj, QString("OAIBTCompanySummaryInfo"));
    }
    if(m_company_plan_isSet){
        obj.insert("companyPlan", QJsonValue(company_plan));
    }
    if(email != nullptr && *email != QString("")){
        toJsonValue(QString("email"), email, obj, QString("QString"));
    }
    if(first_name != nullptr && *first_name != QString("")){
        toJsonValue(QString("firstName"), first_name, obj, QString("QString"));
    }
    if((global_permissions != nullptr) && (global_permissions->isSet())){
        toJsonValue(QString("globalPermissions"), global_permissions, obj, QString("OAIGlobalPermissionInfo"));
    }
    if(href != nullptr && *href != QString("")){
        toJsonValue(QString("href"), href, obj, QString("QString"));
    }
    if(id != nullptr && *id != QString("")){
        toJsonValue(QString("id"), id, obj, QString("QString"));
    }
    if(image != nullptr && *image != QString("")){
        toJsonValue(QString("image"), image, obj, QString("QString"));
    }
    if(m_is_guest_isSet){
        obj.insert("isGuest", QJsonValue(is_guest));
    }
    if(m_is_light_isSet){
        obj.insert("isLight", QJsonValue(is_light));
    }
    if(last_login_time != nullptr) { 
        toJsonValue(QString("lastLoginTime"), last_login_time, obj, QString("QDateTime"));
    }
    if(last_name != nullptr && *last_name != QString("")){
        toJsonValue(QString("lastName"), last_name, obj, QString("QString"));
    }
    if(name != nullptr && *name != QString("")){
        toJsonValue(QString("name"), name, obj, QString("QString"));
    }
    if(m_oauth2_scopes_isSet){
        obj.insert("oauth2Scopes", QJsonValue(oauth2_scopes));
    }
    if(plan_group != nullptr && *plan_group != QString("")){
        toJsonValue(QString("planGroup"), plan_group, obj, QString("QString"));
    }
    if(m_role_isSet){
        obj.insert("role", QJsonValue(role));
    }
    if(roles->size() > 0){
        toJsonArray((QList<void*>*)roles, obj, "roles", "QString");
    }
    if(m_source_isSet){
        obj.insert("source", QJsonValue(source));
    }
    if(m_state_isSet){
        obj.insert("state", QJsonValue(state));
    }
    if(view_ref != nullptr && *view_ref != QString("")){
        toJsonValue(QString("viewRef"), view_ref, obj, QString("QString"));
    }

    return obj;
}

QString*
OAIBTUserOAuth2SummaryInfo::getClientId() {
    return client_id;
}
void
OAIBTUserOAuth2SummaryInfo::setClientId(QString* client_id) {
    this->client_id = client_id;
    this->m_client_id_isSet = true;
}

OAIBTCompanySummaryInfo*
OAIBTUserOAuth2SummaryInfo::getCompany() {
    return company;
}
void
OAIBTUserOAuth2SummaryInfo::setCompany(OAIBTCompanySummaryInfo* company) {
    this->company = company;
    this->m_company_isSet = true;
}

bool
OAIBTUserOAuth2SummaryInfo::isCompanyPlan() {
    return company_plan;
}
void
OAIBTUserOAuth2SummaryInfo::setCompanyPlan(bool company_plan) {
    this->company_plan = company_plan;
    this->m_company_plan_isSet = true;
}

QString*
OAIBTUserOAuth2SummaryInfo::getEmail() {
    return email;
}
void
OAIBTUserOAuth2SummaryInfo::setEmail(QString* email) {
    this->email = email;
    this->m_email_isSet = true;
}

QString*
OAIBTUserOAuth2SummaryInfo::getFirstName() {
    return first_name;
}
void
OAIBTUserOAuth2SummaryInfo::setFirstName(QString* first_name) {
    this->first_name = first_name;
    this->m_first_name_isSet = true;
}

OAIGlobalPermissionInfo*
OAIBTUserOAuth2SummaryInfo::getGlobalPermissions() {
    return global_permissions;
}
void
OAIBTUserOAuth2SummaryInfo::setGlobalPermissions(OAIGlobalPermissionInfo* global_permissions) {
    this->global_permissions = global_permissions;
    this->m_global_permissions_isSet = true;
}

QString*
OAIBTUserOAuth2SummaryInfo::getHref() {
    return href;
}
void
OAIBTUserOAuth2SummaryInfo::setHref(QString* href) {
    this->href = href;
    this->m_href_isSet = true;
}

QString*
OAIBTUserOAuth2SummaryInfo::getId() {
    return id;
}
void
OAIBTUserOAuth2SummaryInfo::setId(QString* id) {
    this->id = id;
    this->m_id_isSet = true;
}

QString*
OAIBTUserOAuth2SummaryInfo::getImage() {
    return image;
}
void
OAIBTUserOAuth2SummaryInfo::setImage(QString* image) {
    this->image = image;
    this->m_image_isSet = true;
}

bool
OAIBTUserOAuth2SummaryInfo::isIsGuest() {
    return is_guest;
}
void
OAIBTUserOAuth2SummaryInfo::setIsGuest(bool is_guest) {
    this->is_guest = is_guest;
    this->m_is_guest_isSet = true;
}

bool
OAIBTUserOAuth2SummaryInfo::isIsLight() {
    return is_light;
}
void
OAIBTUserOAuth2SummaryInfo::setIsLight(bool is_light) {
    this->is_light = is_light;
    this->m_is_light_isSet = true;
}

QDateTime*
OAIBTUserOAuth2SummaryInfo::getLastLoginTime() {
    return last_login_time;
}
void
OAIBTUserOAuth2SummaryInfo::setLastLoginTime(QDateTime* last_login_time) {
    this->last_login_time = last_login_time;
    this->m_last_login_time_isSet = true;
}

QString*
OAIBTUserOAuth2SummaryInfo::getLastName() {
    return last_name;
}
void
OAIBTUserOAuth2SummaryInfo::setLastName(QString* last_name) {
    this->last_name = last_name;
    this->m_last_name_isSet = true;
}

QString*
OAIBTUserOAuth2SummaryInfo::getName() {
    return name;
}
void
OAIBTUserOAuth2SummaryInfo::setName(QString* name) {
    this->name = name;
    this->m_name_isSet = true;
}

qint64
OAIBTUserOAuth2SummaryInfo::getOauth2Scopes() {
    return oauth2_scopes;
}
void
OAIBTUserOAuth2SummaryInfo::setOauth2Scopes(qint64 oauth2_scopes) {
    this->oauth2_scopes = oauth2_scopes;
    this->m_oauth2_scopes_isSet = true;
}

QString*
OAIBTUserOAuth2SummaryInfo::getPlanGroup() {
    return plan_group;
}
void
OAIBTUserOAuth2SummaryInfo::setPlanGroup(QString* plan_group) {
    this->plan_group = plan_group;
    this->m_plan_group_isSet = true;
}

qint32
OAIBTUserOAuth2SummaryInfo::getRole() {
    return role;
}
void
OAIBTUserOAuth2SummaryInfo::setRole(qint32 role) {
    this->role = role;
    this->m_role_isSet = true;
}

QList<QString*>*
OAIBTUserOAuth2SummaryInfo::getRoles() {
    return roles;
}
void
OAIBTUserOAuth2SummaryInfo::setRoles(QList<QString*>* roles) {
    this->roles = roles;
    this->m_roles_isSet = true;
}

qint32
OAIBTUserOAuth2SummaryInfo::getSource() {
    return source;
}
void
OAIBTUserOAuth2SummaryInfo::setSource(qint32 source) {
    this->source = source;
    this->m_source_isSet = true;
}

qint32
OAIBTUserOAuth2SummaryInfo::getState() {
    return state;
}
void
OAIBTUserOAuth2SummaryInfo::setState(qint32 state) {
    this->state = state;
    this->m_state_isSet = true;
}

QString*
OAIBTUserOAuth2SummaryInfo::getViewRef() {
    return view_ref;
}
void
OAIBTUserOAuth2SummaryInfo::setViewRef(QString* view_ref) {
    this->view_ref = view_ref;
    this->m_view_ref_isSet = true;
}


bool
OAIBTUserOAuth2SummaryInfo::isSet(){
    bool isObjectUpdated = false;
    do{
        if(client_id != nullptr && *client_id != QString("")){ isObjectUpdated = true; break;}
        if(company != nullptr && company->isSet()){ isObjectUpdated = true; break;}
        if(m_company_plan_isSet){ isObjectUpdated = true; break;}
        if(email != nullptr && *email != QString("")){ isObjectUpdated = true; break;}
        if(first_name != nullptr && *first_name != QString("")){ isObjectUpdated = true; break;}
        if(global_permissions != nullptr && global_permissions->isSet()){ isObjectUpdated = true; break;}
        if(href != nullptr && *href != QString("")){ isObjectUpdated = true; break;}
        if(id != nullptr && *id != QString("")){ isObjectUpdated = true; break;}
        if(image != nullptr && *image != QString("")){ isObjectUpdated = true; break;}
        if(m_is_guest_isSet){ isObjectUpdated = true; break;}
        if(m_is_light_isSet){ isObjectUpdated = true; break;}
        if(last_name != nullptr && *last_name != QString("")){ isObjectUpdated = true; break;}
        if(name != nullptr && *name != QString("")){ isObjectUpdated = true; break;}
        if(m_oauth2_scopes_isSet){ isObjectUpdated = true; break;}
        if(plan_group != nullptr && *plan_group != QString("")){ isObjectUpdated = true; break;}
        if(m_role_isSet){ isObjectUpdated = true; break;}
        if(roles->size() > 0){ isObjectUpdated = true; break;}
        if(m_source_isSet){ isObjectUpdated = true; break;}
        if(m_state_isSet){ isObjectUpdated = true; break;}
        if(view_ref != nullptr && *view_ref != QString("")){ isObjectUpdated = true; break;}
    }while(false);
    return isObjectUpdated;
}
}

