/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.111
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIBTMConfigurationParameter-819.h
 *
 * 
 */

#ifndef OAIBTMConfigurationParameter-819_H_
#define OAIBTMConfigurationParameter-819_H_

#include <QJsonObject>


#include "OAIBTTreeNode-20.h"
#include <QString>

#include "OAIObject.h"

namespace OpenAPI {

class OAIBTMConfigurationParameter-819: public OAIObject {
public:
    OAIBTMConfigurationParameter-819();
    OAIBTMConfigurationParameter-819(QString json);
    ~OAIBTMConfigurationParameter-819();
    void init();
    void cleanup();

    QString asJson () override;
    QJsonObject asJsonObject() override;
    void fromJsonObject(QJsonObject json) override;
    OAIBTMConfigurationParameter-819* fromJson(QString jsonString) override;

    QString* getBtType();
    void setBtType(QString* bt_type);

    OAIBTTreeNode-20* getGeneratedParameterId();
    void setGeneratedParameterId(OAIBTTreeNode-20* generated_parameter_id);

    QString* getImportMicroversion();
    void setImportMicroversion(QString* import_microversion);

    QString* getNodeId();
    void setNodeId(QString* node_id);

    QString* getParameterId();
    void setParameterId(QString* parameter_id);

    QString* getParameterName();
    void setParameterName(QString* parameter_name);

    QString* getParameterType();
    void setParameterType(QString* parameter_type);

    bool isValid();
    void setValid(bool valid);


    virtual bool isSet() override;

private:
    QString* bt_type;
    bool m_bt_type_isSet;

    OAIBTTreeNode-20* generated_parameter_id;
    bool m_generated_parameter_id_isSet;

    QString* import_microversion;
    bool m_import_microversion_isSet;

    QString* node_id;
    bool m_node_id_isSet;

    QString* parameter_id;
    bool m_parameter_id_isSet;

    QString* parameter_name;
    bool m_parameter_name_isSet;

    QString* parameter_type;
    bool m_parameter_type_isSet;

    bool valid;
    bool m_valid_isSet;

};

}

#endif /* OAIBTMConfigurationParameter-819_H_ */
