/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.111
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


#include "OAIBTDefaultUnitsInfo.h"

#include "OAIHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace OpenAPI {

OAIBTDefaultUnitsInfo::OAIBTDefaultUnitsInfo(QString json) {
    init();
    this->fromJson(json);
}

OAIBTDefaultUnitsInfo::OAIBTDefaultUnitsInfo() {
    init();
}

OAIBTDefaultUnitsInfo::~OAIBTDefaultUnitsInfo() {
    this->cleanup();
}

void
OAIBTDefaultUnitsInfo::init() {
    node_id = new QString("");
    m_node_id_isSet = false;
    units = new QList<OAIBTDefaultUnitInfo*>();
    m_units_isSet = false;
}

void
OAIBTDefaultUnitsInfo::cleanup() {
    if(node_id != nullptr) { 
        delete node_id;
    }
    if(units != nullptr) { 
        auto arr = units;
        for(auto o: *arr) { 
            delete o;
        }
        delete units;
    }
}

OAIBTDefaultUnitsInfo*
OAIBTDefaultUnitsInfo::fromJson(QString json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
OAIBTDefaultUnitsInfo::fromJsonObject(QJsonObject pJson) {
    ::OpenAPI::setValue(&node_id, pJson["nodeId"], "QString", "QString");
    
    
    ::OpenAPI::setValue(&units, pJson["units"], "QList", "OAIBTDefaultUnitInfo");
}

QString
OAIBTDefaultUnitsInfo::asJson ()
{
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject
OAIBTDefaultUnitsInfo::asJsonObject() {
    QJsonObject obj;
    if(node_id != nullptr && *node_id != QString("")){
        toJsonValue(QString("nodeId"), node_id, obj, QString("QString"));
    }
    if(units->size() > 0){
        toJsonArray((QList<void*>*)units, obj, "units", "OAIBTDefaultUnitInfo");
    }

    return obj;
}

QString*
OAIBTDefaultUnitsInfo::getNodeId() {
    return node_id;
}
void
OAIBTDefaultUnitsInfo::setNodeId(QString* node_id) {
    this->node_id = node_id;
    this->m_node_id_isSet = true;
}

QList<OAIBTDefaultUnitInfo*>*
OAIBTDefaultUnitsInfo::getUnits() {
    return units;
}
void
OAIBTDefaultUnitsInfo::setUnits(QList<OAIBTDefaultUnitInfo*>* units) {
    this->units = units;
    this->m_units_isSet = true;
}


bool
OAIBTDefaultUnitsInfo::isSet(){
    bool isObjectUpdated = false;
    do{
        if(node_id != nullptr && *node_id != QString("")){ isObjectUpdated = true; break;}
        if(units->size() > 0){ isObjectUpdated = true; break;}
    }while(false);
    return isObjectUpdated;
}
}

