/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.111
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIBTConstructionObjectFilter-113.h
 *
 * 
 */

#ifndef OAIBTConstructionObjectFilter-113_H_
#define OAIBTConstructionObjectFilter-113_H_

#include <QJsonObject>


#include "OAIBTQueryFilter-183.h"
#include <QString>

#include "OAIObject.h"

namespace OpenAPI {

class OAIBTConstructionObjectFilter-113: public OAIObject {
public:
    OAIBTConstructionObjectFilter-113();
    OAIBTConstructionObjectFilter-113(QString json);
    ~OAIBTConstructionObjectFilter-113();
    void init();
    void cleanup();

    QString asJson () override;
    QJsonObject asJsonObject() override;
    void fromJsonObject(QJsonObject json) override;
    OAIBTConstructionObjectFilter-113* fromJson(QString jsonString) override;

    QString* getBtType();
    void setBtType(QString* bt_type);

    bool isIsConstruction();
    void setIsConstruction(bool is_construction);


    virtual bool isSet() override;

private:
    QString* bt_type;
    bool m_bt_type_isSet;

    bool is_construction;
    bool m_is_construction_isSet;

};

}

#endif /* OAIBTConstructionObjectFilter-113_H_ */
