/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.111
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIBTDocumentParams.h
 *
 * 
 */

#ifndef OAIBTDocumentParams_H_
#define OAIBTDocumentParams_H_

#include <QJsonObject>


#include <QList>
#include <QString>

#include "OAIObject.h"

namespace OpenAPI {

class OAIBTDocumentParams: public OAIObject {
public:
    OAIBTDocumentParams();
    OAIBTDocumentParams(QString json);
    ~OAIBTDocumentParams();
    void init();
    void cleanup();

    QString asJson () override;
    QJsonObject asJsonObject() override;
    void fromJsonObject(QJsonObject json) override;
    OAIBTDocumentParams* fromJson(QString jsonString) override;

    QList<QString*>* getBetaCapabilityIds();
    void setBetaCapabilityIds(QList<QString*>* beta_capability_ids);

    QString* getDescription();
    void setDescription(QString* description);

    bool isGenerateUnknownMessages();
    void setGenerateUnknownMessages(bool generate_unknown_messages);

    bool isIsEmptyContent();
    void setIsEmptyContent(bool is_empty_content);

    bool isIsPublic();
    void setIsPublic(bool is_public);

    QString* getName();
    void setName(QString* name);

    bool isNotRevisionManaged();
    void setNotRevisionManaged(bool not_revision_managed);

    QString* getOwnerEmail();
    void setOwnerEmail(QString* owner_email);

    QString* getOwnerId();
    void setOwnerId(QString* owner_id);

    qint32 getOwnerType();
    void setOwnerType(qint32 owner_type);

    QString* getParentId();
    void setParentId(QString* parent_id);

    QString* getProjectId();
    void setProjectId(QString* project_id);

    QList<QString*>* getTags();
    void setTags(QList<QString*>* tags);


    virtual bool isSet() override;

private:
    QList<QString*>* beta_capability_ids;
    bool m_beta_capability_ids_isSet;

    QString* description;
    bool m_description_isSet;

    bool generate_unknown_messages;
    bool m_generate_unknown_messages_isSet;

    bool is_empty_content;
    bool m_is_empty_content_isSet;

    bool is_public;
    bool m_is_public_isSet;

    QString* name;
    bool m_name_isSet;

    bool not_revision_managed;
    bool m_not_revision_managed_isSet;

    QString* owner_email;
    bool m_owner_email_isSet;

    QString* owner_id;
    bool m_owner_id_isSet;

    qint32 owner_type;
    bool m_owner_type_isSet;

    QString* parent_id;
    bool m_parent_id_isSet;

    QString* project_id;
    bool m_project_id_isSet;

    QList<QString*>* tags;
    bool m_tags_isSet;

};

}

#endif /* OAIBTDocumentParams_H_ */
