/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.111
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


#include "OAIBTUserAppSettingsParams.h"

#include "OAIHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace OpenAPI {

OAIBTUserAppSettingsParams::OAIBTUserAppSettingsParams(QString json) {
    init();
    this->fromJson(json);
}

OAIBTUserAppSettingsParams::OAIBTUserAppSettingsParams() {
    init();
}

OAIBTUserAppSettingsParams::~OAIBTUserAppSettingsParams() {
    this->cleanup();
}

void
OAIBTUserAppSettingsParams::init() {
    settings = new QList<OAIBTSettingParam*>();
    m_settings_isSet = false;
}

void
OAIBTUserAppSettingsParams::cleanup() {
    if(settings != nullptr) { 
        auto arr = settings;
        for(auto o: *arr) { 
            delete o;
        }
        delete settings;
    }
}

OAIBTUserAppSettingsParams*
OAIBTUserAppSettingsParams::fromJson(QString json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
OAIBTUserAppSettingsParams::fromJsonObject(QJsonObject pJson) {
    
    ::OpenAPI::setValue(&settings, pJson["settings"], "QList", "OAIBTSettingParam");
}

QString
OAIBTUserAppSettingsParams::asJson ()
{
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject
OAIBTUserAppSettingsParams::asJsonObject() {
    QJsonObject obj;
    if(settings->size() > 0){
        toJsonArray((QList<void*>*)settings, obj, "settings", "OAIBTSettingParam");
    }

    return obj;
}

QList<OAIBTSettingParam*>*
OAIBTUserAppSettingsParams::getSettings() {
    return settings;
}
void
OAIBTUserAppSettingsParams::setSettings(QList<OAIBTSettingParam*>* settings) {
    this->settings = settings;
    this->m_settings_isSet = true;
}


bool
OAIBTUserAppSettingsParams::isSet(){
    bool isObjectUpdated = false;
    do{
        if(settings->size() > 0){ isObjectUpdated = true; break;}
    }while(false);
    return isObjectUpdated;
}
}

