/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.111
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIBTUserSummaryInfo.h
 *
 * 
 */

#ifndef OAIBTUserSummaryInfo_H_
#define OAIBTUserSummaryInfo_H_

#include <QJsonObject>


#include "OAIBTCompanySummaryInfo.h"
#include "OAIGlobalPermissionInfo.h"
#include <QDateTime>
#include <QString>

#include "OAIObject.h"

namespace OpenAPI {

class OAIBTUserSummaryInfo: public OAIObject {
public:
    OAIBTUserSummaryInfo();
    OAIBTUserSummaryInfo(QString json);
    ~OAIBTUserSummaryInfo();
    void init();
    void cleanup();

    QString asJson () override;
    QJsonObject asJsonObject() override;
    void fromJsonObject(QJsonObject json) override;
    OAIBTUserSummaryInfo* fromJson(QString jsonString) override;

    OAIBTCompanySummaryInfo* getCompany();
    void setCompany(OAIBTCompanySummaryInfo* company);

    QString* getEmail();
    void setEmail(QString* email);

    QString* getFirstName();
    void setFirstName(QString* first_name);

    OAIGlobalPermissionInfo* getGlobalPermissions();
    void setGlobalPermissions(OAIGlobalPermissionInfo* global_permissions);

    QString* getHref();
    void setHref(QString* href);

    QString* getId();
    void setId(QString* id);

    QString* getImage();
    void setImage(QString* image);

    bool isIsGuest();
    void setIsGuest(bool is_guest);

    bool isIsLight();
    void setIsLight(bool is_light);

    QDateTime* getLastLoginTime();
    void setLastLoginTime(QDateTime* last_login_time);

    QString* getLastName();
    void setLastName(QString* last_name);

    QString* getName();
    void setName(QString* name);

    qint32 getSource();
    void setSource(qint32 source);

    qint32 getState();
    void setState(qint32 state);

    QString* getViewRef();
    void setViewRef(QString* view_ref);


    virtual bool isSet() override;

private:
    OAIBTCompanySummaryInfo* company;
    bool m_company_isSet;

    QString* email;
    bool m_email_isSet;

    QString* first_name;
    bool m_first_name_isSet;

    OAIGlobalPermissionInfo* global_permissions;
    bool m_global_permissions_isSet;

    QString* href;
    bool m_href_isSet;

    QString* id;
    bool m_id_isSet;

    QString* image;
    bool m_image_isSet;

    bool is_guest;
    bool m_is_guest_isSet;

    bool is_light;
    bool m_is_light_isSet;

    QDateTime* last_login_time;
    bool m_last_login_time_isSet;

    QString* last_name;
    bool m_last_name_isSet;

    QString* name;
    bool m_name_isSet;

    qint32 source;
    bool m_source_isSet;

    qint32 state;
    bool m_state_isSet;

    QString* view_ref;
    bool m_view_ref_isSet;

};

}

#endif /* OAIBTUserSummaryInfo_H_ */
