/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.111
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


#include "OAIBTFSValueBoolean-1195.h"

#include "OAIHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace OpenAPI {

OAIBTFSValueBoolean-1195::OAIBTFSValueBoolean-1195(QString json) {
    init();
    this->fromJson(json);
}

OAIBTFSValueBoolean-1195::OAIBTFSValueBoolean-1195() {
    init();
}

OAIBTFSValueBoolean-1195::~OAIBTFSValueBoolean-1195() {
    this->cleanup();
}

void
OAIBTFSValueBoolean-1195::init() {
    bt_type = new QString("");
    m_bt_type_isSet = false;
    configuration_value_string = new QString("");
    m_configuration_value_string_isSet = false;
    type_tag = new QString("");
    m_type_tag_isSet = false;
    value_object = false;
    m_value_object_isSet = false;
    value = false;
    m_value_isSet = false;
}

void
OAIBTFSValueBoolean-1195::cleanup() {
    if(bt_type != nullptr) { 
        delete bt_type;
    }
    if(configuration_value_string != nullptr) { 
        delete configuration_value_string;
    }
    if(type_tag != nullptr) { 
        delete type_tag;
    }


}

OAIBTFSValueBoolean-1195*
OAIBTFSValueBoolean-1195::fromJson(QString json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
OAIBTFSValueBoolean-1195::fromJsonObject(QJsonObject pJson) {
    ::OpenAPI::setValue(&bt_type, pJson["btType"], "QString", "QString");
    
    ::OpenAPI::setValue(&configuration_value_string, pJson["configurationValueString"], "QString", "QString");
    
    ::OpenAPI::setValue(&type_tag, pJson["typeTag"], "QString", "QString");
    
    ::OpenAPI::setValue(&value_object, pJson["valueObject"], "bool", "");
    
    ::OpenAPI::setValue(&value, pJson["value"], "bool", "");
    
}

QString
OAIBTFSValueBoolean-1195::asJson ()
{
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject
OAIBTFSValueBoolean-1195::asJsonObject() {
    QJsonObject obj;
    if(bt_type != nullptr && *bt_type != QString("")){
        toJsonValue(QString("btType"), bt_type, obj, QString("QString"));
    }
    if(configuration_value_string != nullptr && *configuration_value_string != QString("")){
        toJsonValue(QString("configurationValueString"), configuration_value_string, obj, QString("QString"));
    }
    if(type_tag != nullptr && *type_tag != QString("")){
        toJsonValue(QString("typeTag"), type_tag, obj, QString("QString"));
    }
    if(m_value_object_isSet){
        obj.insert("valueObject", QJsonValue(value_object));
    }
    if(m_value_isSet){
        obj.insert("value", QJsonValue(value));
    }

    return obj;
}

QString*
OAIBTFSValueBoolean-1195::getBtType() {
    return bt_type;
}
void
OAIBTFSValueBoolean-1195::setBtType(QString* bt_type) {
    this->bt_type = bt_type;
    this->m_bt_type_isSet = true;
}

QString*
OAIBTFSValueBoolean-1195::getConfigurationValueString() {
    return configuration_value_string;
}
void
OAIBTFSValueBoolean-1195::setConfigurationValueString(QString* configuration_value_string) {
    this->configuration_value_string = configuration_value_string;
    this->m_configuration_value_string_isSet = true;
}

QString*
OAIBTFSValueBoolean-1195::getTypeTag() {
    return type_tag;
}
void
OAIBTFSValueBoolean-1195::setTypeTag(QString* type_tag) {
    this->type_tag = type_tag;
    this->m_type_tag_isSet = true;
}

bool
OAIBTFSValueBoolean-1195::isValueObject() {
    return value_object;
}
void
OAIBTFSValueBoolean-1195::setValueObject(bool value_object) {
    this->value_object = value_object;
    this->m_value_object_isSet = true;
}

bool
OAIBTFSValueBoolean-1195::isValue() {
    return value;
}
void
OAIBTFSValueBoolean-1195::setValue(bool value) {
    this->value = value;
    this->m_value_isSet = true;
}


bool
OAIBTFSValueBoolean-1195::isSet(){
    bool isObjectUpdated = false;
    do{
        if(bt_type != nullptr && *bt_type != QString("")){ isObjectUpdated = true; break;}
        if(configuration_value_string != nullptr && *configuration_value_string != QString("")){ isObjectUpdated = true; break;}
        if(type_tag != nullptr && *type_tag != QString("")){ isObjectUpdated = true; break;}
        if(m_value_object_isSet){ isObjectUpdated = true; break;}
        if(m_value_isSet){ isObjectUpdated = true; break;}
    }while(false);
    return isObjectUpdated;
}
}

