/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.111
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIBTMDatabaseParameter-2229.h
 *
 * 
 */

#ifndef OAIBTMDatabaseParameter-2229_H_
#define OAIBTMDatabaseParameter-2229_H_

#include <QJsonObject>


#include "OAIBTMParameter-1.h"
#include <QString>

#include "OAIObject.h"

namespace OpenAPI {

class OAIBTMDatabaseParameter-2229: public OAIObject {
public:
    OAIBTMDatabaseParameter-2229();
    OAIBTMDatabaseParameter-2229(QString json);
    ~OAIBTMDatabaseParameter-2229();
    void init();
    void cleanup();

    QString asJson () override;
    QJsonObject asJsonObject() override;
    void fromJsonObject(QJsonObject json) override;
    OAIBTMDatabaseParameter-2229* fromJson(QString jsonString) override;

    QString* getBtType();
    void setBtType(QString* bt_type);

    QString* getImportMicroversion();
    void setImportMicroversion(QString* import_microversion);

    QString* getNodeId();
    void setNodeId(QString* node_id);

    QString* getParameterId();
    void setParameterId(QString* parameter_id);

    QString* getDatabaseId();
    void setDatabaseId(QString* database_id);


    virtual bool isSet() override;

private:
    QString* bt_type;
    bool m_bt_type_isSet;

    QString* import_microversion;
    bool m_import_microversion_isSet;

    QString* node_id;
    bool m_node_id_isSet;

    QString* parameter_id;
    bool m_parameter_id_isSet;

    QString* database_id;
    bool m_database_id_isSet;

};

}

#endif /* OAIBTMDatabaseParameter-2229_H_ */
