/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.111
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


#include "OAIBTCurveGeometry-114.h"

#include "OAIHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace OpenAPI {

OAIBTCurveGeometry-114::OAIBTCurveGeometry-114(QString json) {
    init();
    this->fromJson(json);
}

OAIBTCurveGeometry-114::OAIBTCurveGeometry-114() {
    init();
}

OAIBTCurveGeometry-114::~OAIBTCurveGeometry-114() {
    this->cleanup();
}

void
OAIBTCurveGeometry-114::init() {
    bt_type = new QString("");
    m_bt_type_isSet = false;
}

void
OAIBTCurveGeometry-114::cleanup() {
    if(bt_type != nullptr) { 
        delete bt_type;
    }
}

OAIBTCurveGeometry-114*
OAIBTCurveGeometry-114::fromJson(QString json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
OAIBTCurveGeometry-114::fromJsonObject(QJsonObject pJson) {
    ::OpenAPI::setValue(&bt_type, pJson["btType"], "QString", "QString");
    
}

QString
OAIBTCurveGeometry-114::asJson ()
{
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject
OAIBTCurveGeometry-114::asJsonObject() {
    QJsonObject obj;
    if(bt_type != nullptr && *bt_type != QString("")){
        toJsonValue(QString("btType"), bt_type, obj, QString("QString"));
    }

    return obj;
}

QString*
OAIBTCurveGeometry-114::getBtType() {
    return bt_type;
}
void
OAIBTCurveGeometry-114::setBtType(QString* bt_type) {
    this->bt_type = bt_type;
    this->m_bt_type_isSet = true;
}


bool
OAIBTCurveGeometry-114::isSet(){
    bool isObjectUpdated = false;
    do{
        if(bt_type != nullptr && *bt_type != QString("")){ isObjectUpdated = true; break;}
    }while(false);
    return isObjectUpdated;
}
}

