/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.111
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


#include "OAIBTFSTableRowMetadata-2262.h"

#include "OAIHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace OpenAPI {

OAIBTFSTableRowMetadata-2262::OAIBTFSTableRowMetadata-2262(QString json) {
    init();
    this->fromJson(json);
}

OAIBTFSTableRowMetadata-2262::OAIBTFSTableRowMetadata-2262() {
    init();
}

OAIBTFSTableRowMetadata-2262::~OAIBTFSTableRowMetadata-2262() {
    this->cleanup();
}

void
OAIBTFSTableRowMetadata-2262::init() {
    bt_type = new QString("");
    m_bt_type_isSet = false;
    cross_highlight_data_if_any = new OAIBTTableBaseCrossHighlightData-2609();
    m_cross_highlight_data_if_any_isSet = false;
    callout = new QString("");
    m_callout_isSet = false;
    cross_highlight_data = new OAIBTTableBaseCrossHighlightData-2609();
    m_cross_highlight_data_isSet = false;
}

void
OAIBTFSTableRowMetadata-2262::cleanup() {
    if(bt_type != nullptr) { 
        delete bt_type;
    }
    if(cross_highlight_data_if_any != nullptr) { 
        delete cross_highlight_data_if_any;
    }
    if(callout != nullptr) { 
        delete callout;
    }
    if(cross_highlight_data != nullptr) { 
        delete cross_highlight_data;
    }
}

OAIBTFSTableRowMetadata-2262*
OAIBTFSTableRowMetadata-2262::fromJson(QString json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
OAIBTFSTableRowMetadata-2262::fromJsonObject(QJsonObject pJson) {
    ::OpenAPI::setValue(&bt_type, pJson["btType"], "QString", "QString");
    
    ::OpenAPI::setValue(&cross_highlight_data_if_any, pJson["crossHighlightDataIfAny"], "OAIBTTableBaseCrossHighlightData-2609", "OAIBTTableBaseCrossHighlightData-2609");
    
    ::OpenAPI::setValue(&callout, pJson["callout"], "QString", "QString");
    
    ::OpenAPI::setValue(&cross_highlight_data, pJson["crossHighlightData"], "OAIBTTableBaseCrossHighlightData-2609", "OAIBTTableBaseCrossHighlightData-2609");
    
}

QString
OAIBTFSTableRowMetadata-2262::asJson ()
{
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject
OAIBTFSTableRowMetadata-2262::asJsonObject() {
    QJsonObject obj;
    if(bt_type != nullptr && *bt_type != QString("")){
        toJsonValue(QString("btType"), bt_type, obj, QString("QString"));
    }
    if((cross_highlight_data_if_any != nullptr) && (cross_highlight_data_if_any->isSet())){
        toJsonValue(QString("crossHighlightDataIfAny"), cross_highlight_data_if_any, obj, QString("OAIBTTableBaseCrossHighlightData-2609"));
    }
    if(callout != nullptr && *callout != QString("")){
        toJsonValue(QString("callout"), callout, obj, QString("QString"));
    }
    if((cross_highlight_data != nullptr) && (cross_highlight_data->isSet())){
        toJsonValue(QString("crossHighlightData"), cross_highlight_data, obj, QString("OAIBTTableBaseCrossHighlightData-2609"));
    }

    return obj;
}

QString*
OAIBTFSTableRowMetadata-2262::getBtType() {
    return bt_type;
}
void
OAIBTFSTableRowMetadata-2262::setBtType(QString* bt_type) {
    this->bt_type = bt_type;
    this->m_bt_type_isSet = true;
}

OAIBTTableBaseCrossHighlightData-2609*
OAIBTFSTableRowMetadata-2262::getCrossHighlightDataIfAny() {
    return cross_highlight_data_if_any;
}
void
OAIBTFSTableRowMetadata-2262::setCrossHighlightDataIfAny(OAIBTTableBaseCrossHighlightData-2609* cross_highlight_data_if_any) {
    this->cross_highlight_data_if_any = cross_highlight_data_if_any;
    this->m_cross_highlight_data_if_any_isSet = true;
}

QString*
OAIBTFSTableRowMetadata-2262::getCallout() {
    return callout;
}
void
OAIBTFSTableRowMetadata-2262::setCallout(QString* callout) {
    this->callout = callout;
    this->m_callout_isSet = true;
}

OAIBTTableBaseCrossHighlightData-2609*
OAIBTFSTableRowMetadata-2262::getCrossHighlightData() {
    return cross_highlight_data;
}
void
OAIBTFSTableRowMetadata-2262::setCrossHighlightData(OAIBTTableBaseCrossHighlightData-2609* cross_highlight_data) {
    this->cross_highlight_data = cross_highlight_data;
    this->m_cross_highlight_data_isSet = true;
}


bool
OAIBTFSTableRowMetadata-2262::isSet(){
    bool isObjectUpdated = false;
    do{
        if(bt_type != nullptr && *bt_type != QString("")){ isObjectUpdated = true; break;}
        if(cross_highlight_data_if_any != nullptr && cross_highlight_data_if_any->isSet()){ isObjectUpdated = true; break;}
        if(callout != nullptr && *callout != QString("")){ isObjectUpdated = true; break;}
        if(cross_highlight_data != nullptr && cross_highlight_data->isSet()){ isObjectUpdated = true; break;}
    }while(false);
    return isObjectUpdated;
}
}

