/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.111
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAICoupon.h
 *
 * 
 */

#ifndef OAICoupon_H_
#define OAICoupon_H_

#include <QJsonObject>


#include <QList>
#include <QMap>
#include <QString>

#include "OAIObject.h"

namespace OpenAPI {

class OAICoupon: public OAIObject {
public:
    OAICoupon();
    OAICoupon(QString json);
    ~OAICoupon();
    void init();
    void cleanup();

    QString asJson () override;
    QJsonObject asJsonObject() override;
    void fromJsonObject(QJsonObject json) override;
    OAICoupon* fromJson(QString jsonString) override;

    qint64 getAmountOff();
    void setAmountOff(qint64 amount_off);

    qint64 getCreated();
    void setCreated(qint64 created);

    QString* getCurrency();
    void setCurrency(QString* currency);

    QString* getDuration();
    void setDuration(QString* duration);

    qint32 getDurationInMonths();
    void setDurationInMonths(qint32 duration_in_months);

    QString* getId();
    void setId(QString* id);

    bool isLivemode();
    void setLivemode(bool livemode);

    qint64 getMaxRedemptions();
    void setMaxRedemptions(qint64 max_redemptions);

    QMap<QString, QString*>* getMetadata();
    void setMetadata(QMap<QString, QString*>* metadata);

    QString* getObject();
    void setObject(QString* object);

    qint32 getPercentOff();
    void setPercentOff(qint32 percent_off);

    qint64 getRedeemBy();
    void setRedeemBy(qint64 redeem_by);

    qint32 getTimesRedeemed();
    void setTimesRedeemed(qint32 times_redeemed);

    bool isValid();
    void setValid(bool valid);


    virtual bool isSet() override;

private:
    qint64 amount_off;
    bool m_amount_off_isSet;

    qint64 created;
    bool m_created_isSet;

    QString* currency;
    bool m_currency_isSet;

    QString* duration;
    bool m_duration_isSet;

    qint32 duration_in_months;
    bool m_duration_in_months_isSet;

    QString* id;
    bool m_id_isSet;

    bool livemode;
    bool m_livemode_isSet;

    qint64 max_redemptions;
    bool m_max_redemptions_isSet;

    QMap<QString, QString*>* metadata;
    bool m_metadata_isSet;

    QString* object;
    bool m_object_isSet;

    qint32 percent_off;
    bool m_percent_off_isSet;

    qint64 redeem_by;
    bool m_redeem_by_isSet;

    qint32 times_redeemed;
    bool m_times_redeemed_isSet;

    bool valid;
    bool m_valid_isSet;

};

}

#endif /* OAICoupon_H_ */
