/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.111
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIOperation_responses.h
 *
 * 
 */

#ifndef OAIOperation_responses_H_
#define OAIOperation_responses_H_

#include <QJsonObject>


#include "OAIApiResponse.h"
#include "OAIObject.h"
#include <QList>
#include <QMap>

#include "OAIObject.h"

namespace OpenAPI {

class OAIOperation_responses: public OAIObject {
public:
    OAIOperation_responses();
    OAIOperation_responses(QString json);
    ~OAIOperation_responses();
    void init();
    void cleanup();

    QString asJson () override;
    QJsonObject asJsonObject() override;
    void fromJsonObject(QJsonObject json) override;
    OAIOperation_responses* fromJson(QString jsonString) override;

    QMap<QString, OAIObject*>* getExtensions();
    void setExtensions(QMap<QString, OAIObject*>* extensions);

    OAIApiResponse* getDefault();
    void setDefault(OAIApiResponse* _default);

    bool isEmpty();
    void setEmpty(bool empty);


    virtual bool isSet() override;

private:
    QMap<QString, OAIObject*>* extensions;
    bool m_extensions_isSet;

    OAIApiResponse* _default;
    bool m__default_isSet;

    bool empty;
    bool m_empty_isSet;

};

}

#endif /* OAIOperation_responses_H_ */
