/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.111
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAISecurityScheme.h
 *
 * 
 */

#ifndef OAISecurityScheme_H_
#define OAISecurityScheme_H_

#include <QJsonObject>


#include "OAIOAuthFlows.h"
#include "OAIObject.h"
#include <QList>
#include <QMap>
#include <QString>

#include "OAIObject.h"

namespace OpenAPI {

class OAISecurityScheme: public OAIObject {
public:
    OAISecurityScheme();
    OAISecurityScheme(QString json);
    ~OAISecurityScheme();
    void init();
    void cleanup();

    QString asJson () override;
    QJsonObject asJsonObject() override;
    void fromJsonObject(QJsonObject json) override;
    OAISecurityScheme* fromJson(QString jsonString) override;

    QString* getBearerFormat();
    void setBearerFormat(QString* bearer_format);

    QString* getDescription();
    void setDescription(QString* description);

    QMap<QString, OAIObject*>* getExtensions();
    void setExtensions(QMap<QString, OAIObject*>* extensions);

    OAIOAuthFlows* getFlows();
    void setFlows(OAIOAuthFlows* flows);

    QString* getGetref();
    void setGetref(QString* getref);

    QString* getIn();
    void setIn(QString* in);

    QString* getName();
    void setName(QString* name);

    QString* getOpenIdConnectUrl();
    void setOpenIdConnectUrl(QString* open_id_connect_url);

    QString* getScheme();
    void setScheme(QString* scheme);

    QString* getType();
    void setType(QString* type);


    virtual bool isSet() override;

private:
    QString* bearer_format;
    bool m_bearer_format_isSet;

    QString* description;
    bool m_description_isSet;

    QMap<QString, OAIObject*>* extensions;
    bool m_extensions_isSet;

    OAIOAuthFlows* flows;
    bool m_flows_isSet;

    QString* getref;
    bool m_getref_isSet;

    QString* in;
    bool m_in_isSet;

    QString* name;
    bool m_name_isSet;

    QString* open_id_connect_url;
    bool m_open_id_connect_url_isSet;

    QString* scheme;
    bool m_scheme_isSet;

    QString* type;
    bool m_type_isSet;

};

}

#endif /* OAISecurityScheme_H_ */
