/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.111
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAITag.h
 *
 * 
 */

#ifndef OAITag_H_
#define OAITag_H_

#include <QJsonObject>


#include "OAIExternalDocumentation.h"
#include "OAIObject.h"
#include <QList>
#include <QMap>
#include <QString>

#include "OAIObject.h"

namespace OpenAPI {

class OAITag: public OAIObject {
public:
    OAITag();
    OAITag(QString json);
    ~OAITag();
    void init();
    void cleanup();

    QString asJson () override;
    QJsonObject asJsonObject() override;
    void fromJsonObject(QJsonObject json) override;
    OAITag* fromJson(QString jsonString) override;

    QString* getDescription();
    void setDescription(QString* description);

    QMap<QString, OAIObject*>* getExtensions();
    void setExtensions(QMap<QString, OAIObject*>* extensions);

    OAIExternalDocumentation* getExternalDocs();
    void setExternalDocs(OAIExternalDocumentation* external_docs);

    QString* getName();
    void setName(QString* name);


    virtual bool isSet() override;

private:
    QString* description;
    bool m_description_isSet;

    QMap<QString, OAIObject*>* extensions;
    bool m_extensions_isSet;

    OAIExternalDocumentation* external_docs;
    bool m_external_docs_isSet;

    QString* name;
    bool m_name_isSet;

};

}

#endif /* OAITag_H_ */
