/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.111
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIWorkflowApi.h"
#include "OAIHelpers.h"
#include "OAIModelFactory.h"
#include "OAIQObjectWrapper.h"

#include <QJsonArray>
#include <QJsonDocument>

namespace OpenAPI {

OAIWorkflowApi::OAIWorkflowApi() {}

OAIWorkflowApi::~OAIWorkflowApi() {}

OAIWorkflowApi::OAIWorkflowApi(QString host, QString basePath) {
    this->host = host;
    this->basePath = basePath;
}

void
OAIWorkflowApi::getActiveWorkflows(QString* document_id) {
    QString fullPath;
    fullPath.append(this->host).append(this->basePath).append("/api/workflow/active");


    if (fullPath.indexOf("?") > 0)
      fullPath.append("&");
    else
      fullPath.append("?");
    fullPath.append(QUrl::toPercentEncoding("documentId"))
        .append("=")
        .append(QUrl::toPercentEncoding(stringValue(document_id)));


    OAIHttpRequestWorker *worker = new OAIHttpRequestWorker();
    OAIHttpRequestInput input(fullPath, "GET");





    foreach(QString key, this->defaultHeaders.keys()) {
        input.headers.insert(key, this->defaultHeaders.value(key));
    }

    connect(worker,
            &OAIHttpRequestWorker::on_execution_finished,
            this,
            &OAIWorkflowApi::getActiveWorkflowsCallback);

    worker->execute(&input);
}

void
OAIWorkflowApi::getActiveWorkflowsCallback(OAIHttpRequestWorker * worker) {
    QString msg;
    QString error_str = worker->error_str;
    QNetworkReply::NetworkError error_type = worker->error_type;

    if (worker->error_type == QNetworkReply::NoError) {
        msg = QString("Success! %1 bytes").arg(worker->response.length());
    }
    else {
        msg = "Error: " + worker->error_str;
    }

    QString json(worker->response);
    OAIBTActiveWorkflowInfo* output = static_cast<OAIBTActiveWorkflowInfo*>(create(json, QString("OAIBTActiveWorkflowInfo")));
    auto wrapper = new OAIQObjectWrapper<OAIBTActiveWorkflowInfo*> (output);
    wrapper->deleteLater();
    worker->deleteLater();

    if (worker->error_type == QNetworkReply::NoError) {
        emit getActiveWorkflowsSignal(output);
    } else {
        emit getActiveWorkflowsSignalE(output, error_type, error_str);
        emit getActiveWorkflowsSignalEFull(worker, error_type, error_str);
    }
}


}
